In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("match_stats.csv")

In [4]:
df.head()

,Unnamed: 0,PLAYER,MATCHES,INNS,RUNS,AVG,SR,4s,6s
0,0,Vaibhav Sooryavanshi,16,16,776,48.50,237.31,63,72
1,1,Shubman Gill,16,16,732,45.75,163.03,74,33
2,2,Sai Sudharsan,17,17,722,45.12,157.99,75,30
3,3,Virat Kohli,16,16,675,56.25,165.85,73,25
4,4,Heinrich Klaasen,15,15,624,48.00,160.00,48,31

In [5]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [6]:
df

                  PLAYER  MATCHES  INNS  RUNS    AVG      SR  4s  6s
0   Vaibhav Sooryavanshi       16    16   776  48.50  237.31  63  72
1           Shubman Gill       16    16   732  45.75  163.03  74  33
2          Sai Sudharsan       17    17   722  45.12  157.99  75  30
3            Virat Kohli       16    16   675  56.25  165.85  73  25
4       Heinrich Klaasen       15    15   624  48.00  160.00  48  31
5           Ishan Kishan       15    15   602  40.13  182.42  60  32
6               KL Rahul       14    14   593  45.62  174.41  56  31
7        Abhishek Sharma       15    15   563  40.21  204.73  50  43
8         Mitchell Marsh       13    13   563  43.31  163.19  51  36
9            Jos Buttler       17    17   526  37.57  152.46  51  26
10           Dhruv Jurel       16    16   515  36.79  154.65  47  24
11     Prabhsimran Singh       14    13   510  42.50  168.87  55  23
12         Rajat Patidar       15    14   501  41.75  192.69  30  42
13          Shreyas Iyer       14    13   498  55.33  168.81  39  30
14       Cooper Connolly       14    13   491  44.64  163.12  43  32

In [7]:
df.isna().sum()

PLAYER     0
MATCHES    0
INNS       0
RUNS       0
AVG        0
SR         0
4s         0
6s         0
dtype: int64

In [9]:
df.isna().sum()

PLAYER     0
MATCHES    0
INNS       0
RUNS       0
AVG        0
SR         0
4s         0
6s         0
dtype: int64

In [8]:
df.dropna()

                  PLAYER  MATCHES  INNS  RUNS    AVG      SR  4s  6s
0   Vaibhav Sooryavanshi       16    16   776  48.50  237.31  63  72
1           Shubman Gill       16    16   732  45.75  163.03  74  33
2          Sai Sudharsan       17    17   722  45.12  157.99  75  30
3            Virat Kohli       16    16   675  56.25  165.85  73  25
4       Heinrich Klaasen       15    15   624  48.00  160.00  48  31
5           Ishan Kishan       15    15   602  40.13  182.42  60  32
6               KL Rahul       14    14   593  45.62  174.41  56  31
7        Abhishek Sharma       15    15   563  40.21  204.73  50  43
8         Mitchell Marsh       13    13   563  43.31  163.19  51  36
9            Jos Buttler       17    17   526  37.57  152.46  51  26
10           Dhruv Jurel       16    16   515  36.79  154.65  47  24
11     Prabhsimran Singh       14    13   510  42.50  168.87  55  23
12         Rajat Patidar       15    14   501  41.75  192.69  30  42
13          Shreyas Iyer       14    13   498  55.33  168.81  39  30
14       Cooper Connolly       14    13   491  44.64  163.12  43  32

In [10]:
df.dropna(axis=1)

                  PLAYER  MATCHES  INNS  RUNS    AVG      SR  4s  6s
0   Vaibhav Sooryavanshi       16    16   776  48.50  237.31  63  72
1           Shubman Gill       16    16   732  45.75  163.03  74  33
2          Sai Sudharsan       17    17   722  45.12  157.99  75  30
3            Virat Kohli       16    16   675  56.25  165.85  73  25
4       Heinrich Klaasen       15    15   624  48.00  160.00  48  31
5           Ishan Kishan       15    15   602  40.13  182.42  60  32
6               KL Rahul       14    14   593  45.62  174.41  56  31
7        Abhishek Sharma       15    15   563  40.21  204.73  50  43
8         Mitchell Marsh       13    13   563  43.31  163.19  51  36
9            Jos Buttler       17    17   526  37.57  152.46  51  26
10           Dhruv Jurel       16    16   515  36.79  154.65  47  24
11     Prabhsimran Singh       14    13   510  42.50  168.87  55  23
12         Rajat Patidar       15    14   501  41.75  192.69  30  42
13          Shreyas Iyer       14    13   498  55.33  168.81  39  30
14       Cooper Connolly       14    13   491  44.64  163.12  43  32

In [11]:
df.dropna(thresh=5)

                  PLAYER  MATCHES  INNS  RUNS    AVG      SR  4s  6s
0   Vaibhav Sooryavanshi       16    16   776  48.50  237.31  63  72
1           Shubman Gill       16    16   732  45.75  163.03  74  33
2          Sai Sudharsan       17    17   722  45.12  157.99  75  30
3            Virat Kohli       16    16   675  56.25  165.85  73  25
4       Heinrich Klaasen       15    15   624  48.00  160.00  48  31
5           Ishan Kishan       15    15   602  40.13  182.42  60  32
6               KL Rahul       14    14   593  45.62  174.41  56  31
7        Abhishek Sharma       15    15   563  40.21  204.73  50  43
8         Mitchell Marsh       13    13   563  43.31  163.19  51  36
9            Jos Buttler       17    17   526  37.57  152.46  51  26
10           Dhruv Jurel       16    16   515  36.79  154.65  47  24
11     Prabhsimran Singh       14    13   510  42.50  168.87  55  23
12         Rajat Patidar       15    14   501  41.75  192.69  30  42
13          Shreyas Iyer       14    13   498  55.33  168.81  39  30
14       Cooper Connolly       14    13   491  44.64  163.12  43  32

In [1]:
df.fillna(0)

NameError: name 'df' is not defined

In [13]:
df[['MATCHES', 'INNS','RUNS','SR','4s','6s']]

    MATCHES  INNS  RUNS      SR  4s  6s
0        16    16   776  237.31  63  72
1        16    16   732  163.03  74  33
2        17    17   722  157.99  75  30
3        16    16   675  165.85  73  25
4        15    15   624  160.00  48  31
5        15    15   602  182.42  60  32
6        14    14   593  174.41  56  31
7        15    15   563  204.73  50  43
8        13    13   563  163.19  51  36
9        17    17   526  152.46  51  26
10       16    16   515  154.65  47  24
11       14    13   510  168.87  55  23
12       15    14   501  192.69  30  42
13       14    13   498  168.81  39  30
14       14    13   491  163.12  43  32

In [5]:
cols=['MATCHES','INNS','RUNS','SR','4s','6s']
for i in cols:
    df[i] = df[i].fillna(df[i].mean())

In [7]:
df['PLAYER'] = df['PLAYER'].fillna('Unknown')

In [9]:
df.isna().sum()

Unnamed: 0    0
PLAYER        0
MATCHES       0
INNS          0
RUNS          0
AVG           0
SR            0
4s            0
6s            0
dtype: int64

In [10]:
df.to_csv('match_stats.csv')

In [11]:
df = pd.read_csv('match_stats.csv')

In [12]:
df

,Unnamed: 0.1,Unnamed: 0,PLAYER,MATCHES,INNS,RUNS,AVG,SR,4s,6s
0,0,0,Vaibhav Sooryavanshi,16,16,776,48.50,237.31,63,72
1,1,1,Shubman Gill,16,16,732,45.75,163.03,74,33
2,2,2,Sai Sudharsan,17,17,722,45.12,157.99,75,30
3,3,3,Virat Kohli,16,16,675,56.25,165.85,73,25
4,4,4,Heinrich Klaasen,15,15,624,48.00,160.00,48,31
5,5,5,Ishan Kishan,15,15,602,40.13,182.42,60,32
6,6,6,KL Rahul,14,14,593,45.62,174.41,56,31
7,7,7,Abhishek Sharma,15,15,563,40.21,204.73,50,43
8,8,8,Mitchell Marsh,13,13,563,43.31,163.19,51,36
9,9,9,Jos Buttler,17,17,526,37.57,152.46,51,26
10,10,10,Dhruv Jurel,16,16,515,36.79,154.65,47,24
11,11,11,Prabhsimran Singh,14,13,510,42.50,168.87,55,23
12,12,12,Rajat Patidar,15,14,501,41.75,192.69,30,42
13,13,13,Shreyas Iyer,14,13,498,55.33,168.81,39,30
14,14,14,Cooper Connolly,14,13,491,44.64,163.12,43,32

In [53]:
df

,Unnamed: 0,PLAYER,MATCHES,INNS,RUNS,AVG,SR,4s,6s
0,0,Vaibhav Sooryavanshi,16.000000,16,776.000000,48.50,237.310000,54.083333,72.000000
1,1,Shubman Gill,16.000000,16,732.000000,45.75,163.030000,74.000000,33.000000
2,2,Sai Sudharsan,17.000000,17,722.000000,45.12,157.990000,75.000000,30.000000
3,3,Virat Kohli,16.000000,15,593.461538,56.25,173.983333,54.083333,25.000000
4,4,Heinrich Klaasen,15.000000,15,624.000000,48.00,160.000000,48.000000,31.000000
5,5,Ishan Kishan,15.000000,15,602.000000,40.13,182.420000,60.000000,32.000000
6,6,KL Rahul,14.000000,14,593.000000,45.62,174.410000,56.000000,33.333333
7,7,Abhishek Sharma,15.000000,15,563.000000,40.21,204.730000,50.000000,33.333333
8,8,Mitchell Marsh,13.000000,15,563.000000,43.31,173.983333,51.000000,33.333333
9,9,Jos Buttler,17.000000,17,526.000000,37.57,152.460000,51.000000,26.000000
10,10,Dhruv Jurel,16.000000,16,515.000000,36.79,154.650000,47.000000,24.000000
11,11,Prabhsimran Singh,14.000000,13,510.000000,42.50,168.870000,55.000000,23.000000
12,12,Unknown,15.142857,15,593.461538,41.75,173.983333,54.083333,42.000000
13,13,Shreyas Iyer,14.000000,13,498.000000,55.33,168.810000,39.000000,30.000000
14,14,Cooper Connolly,14.000000,13,491.000000,44.64,163.120000,43.000000,32.000000
15,4,Heinrich Klaasen,15.000000,15,624.000000,48.00,160.000000,48.000000,31.000000
16,7,Abhishek Sharma,15.000000,15,563.000000,40.21,204.730000,50.000000,33.333333
17,8,Mitchell Marsh,13.000000,15,563.000000,43.31,173.983333,51.000000,33.333333
18,0,Vaibhav Sooryavanshi,16.000000,16,776.000000,48.50,237.310000,54.083333,72.000000

In [13]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [54]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17     True
18     True
dtype: bool

In [ ]:
df.duplicated(keep='last')

In [ ]:
df.duplicated().sum()

0      True
1     False
2     False
3     False
4      True
5     False
6     False
7      True
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
dtype: bool

In [ ]:
df[df.duplicated(keep='last')]

np.int64(4)

In [ ]:
df.drop_duplicates(keep='last',inplace=True)

,Unnamed: 0,PLAYER,MATCHES,INNS,RUNS,AVG,SR,4s,6s
0,0,Vaibhav Sooryavanshi,16.0,16,776.0,48.50,237.310000,54.083333,72.000000
4,4,Heinrich Klaasen,15.0,15,624.0,48.00,160.000000,48.000000,31.000000
7,7,Abhishek Sharma,15.0,15,563.0,40.21,204.730000,50.000000,33.333333
8,8,Mitchell Marsh,13.0,15,563.0,43.31,173.983333,51.000000,33.333333

In [ ]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
df

In [ ]:
df[['6s']].duplicated()

,PLAYER,MATCHES,INNS,RUNS,AVG,SR,4s,6s
1,Shubman Gill,16.000000,16,732.000000,45.75,163.030000,74.000000,33.000000
2,Sai Sudharsan,17.000000,17,722.000000,45.12,157.990000,75.000000,30.000000
3,Virat Kohli,16.000000,15,593.461538,56.25,173.983333,54.083333,25.000000
5,Ishan Kishan,15.000000,15,602.000000,40.13,182.420000,60.000000,32.000000
6,KL Rahul,14.000000,14,593.000000,45.62,174.410000,56.000000,33.333333
9,Jos Buttler,17.000000,17,526.000000,37.57,152.460000,51.000000,26.000000
10,Dhruv Jurel,16.000000,16,515.000000,36.79,154.650000,47.000000,24.000000
11,Prabhsimran Singh,14.000000,13,510.000000,42.50,168.870000,55.000000,23.000000
12,Unknown,15.142857,15,593.461538,41.75,173.983333,54.083333,42.000000
13,Shreyas Iyer,14.000000,13,498.000000,55.33,168.810000,39.000000,30.000000
14,Cooper Connolly,14.000000,13,491.000000,44.64,163.120000,43.000000,32.000000
15,Heinrich Klaasen,15.000000,15,624.000000,48.00,160.000000,48.000000,31.000000
16,Abhishek Sharma,15.000000,15,563.000000,40.21,204.730000,50.000000,33.333333
17,Mitchell Marsh,13.000000,15,563.000000,43.31,173.983333,51.000000,33.333333
18,Vaibhav Sooryavanshi,16.000000,16,776.000000,48.50,237.310000,54.083333,72.000000

In [14]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,MATCHES,INNS,RUNS,AVG,SR,4s,6s
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,7.000000,7.000000,15.133333,14.866667,592.733333,44.764667,173.968667,54.333333,34.000000
std,4.472136,4.472136,1.187234,1.457330,94.253054,5.629769,22.581307,12.992672,12.005951
min,0.000000,0.000000,13.000000,13.000000,491.000000,36.790000,152.460000,30.000000,23.000000
25%,3.500000,3.500000,14.000000,13.500000,512.500000,40.980000,161.515000,47.500000,28.000000
50%,7.000000,7.000000,15.000000,15.000000,563.000000,44.640000,165.850000,51.000000,31.000000
75%,10.500000,10.500000,16.000000,16.000000,649.500000,46.875000,178.415000,61.500000,34.500000
max,14.000000,14.000000,17.000000,17.000000,776.000000,56.250000,237.310000,75.000000,72.000000

In [62]:
#descriptive - describe()
#informative - info()

In [63]:
df.describe()

,MATCHES,INNS,RUNS,AVG,SR,4s,6s
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,15.142857,15.000000,593.461538,44.764667,173.983333,54.083333,33.333333
std,1.186661,1.309307,88.310018,5.629769,21.722655,9.808585,11.706734
min,13.000000,13.000000,491.000000,36.790000,152.460000,39.000000,23.000000
25%,14.000000,14.500000,520.500000,40.980000,161.515000,49.000000,28.000000
50%,15.000000,15.000000,593.000000,44.640000,168.870000,54.083333,32.000000
75%,16.000000,16.000000,613.000000,46.875000,174.196667,55.500000,33.333333
max,17.000000,17.000000,776.000000,56.250000,237.310000,75.000000,72.000000

In [17]:
!pip install scikit-learn

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Sneh Gurdasani\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn) (2.3.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp313-cp313-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.2 MB 5.9 MB/s eta 0:00:02
   -------- ------------------------------- 1.8/8.2 MB 4.7 MB/s eta 0:00:02
   ------------ --------------------------- 2.6/8.2 MB 4.4 MB/s eta 0:00:02
   ----------------- ---------------------- 3.7/8.2 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.2 MB 4.1 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.2 MB 4.1 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.2 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 4.1 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 3.8 MB/s  0:00:02
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.23.0-py3-none-any.whl (458 kB)
Downloading scipy-1.18.0-cp313-cp313-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
    --------------------------------------- 0.8/36.6 MB 3.9 MB/s eta 0:00:10
   - -------------------------------------- 1.6/36.6 MB 3.9 MB/s eta 0:00:10
   -- ------------------------------------- 2.4/36.6 MB 3.9 MB/s eta 0:00:09
   --- ------------------------------------ 3.1/36.6 MB 3.9 MB/s eta 0:00:09
   ---- ----------------------------------- 3.9/36.6 MB 3.9 MB/s eta 0:00:09
   ----- ---------------------------------- 4.7/36.6 MB 3.9 MB/s eta 0:00:09
   ------ --------------------------------- 5.8/36.6 MB 3.9 MB/s eta 0:00:08
   ------- -------------------------------- 6.6/36.6 MB 3.9 MB/s eta 0:00:08
   -------- ------------------------------- 7.3/36.6 MB 3.9 MB/s eta 0:00:08
   -------- ------------------------------- 8.1/36.6 MB 3.9 MB/s eta 0:00:08
   --------- ------------------------------ 8.9/36.6 MB 3.9 MB/s eta 0:00:08
   ---------- ----------------------------- 9.7/36.6 MB 3.9 MB/s eta 0:00:07
   ----------- ---------------------------- 10.5/36.6 MB 3.9 MB/s eta 0:00:07
   ------------ --------------------------- 11.3/36.6 MB 3.9 MB/s eta 0:00:07
   ------------- -------------------------- 12.1/36.6 MB 3.9 MB/s eta 0:00:07
   -------------- ------------------------- 12.8/36.6 MB 3.9 MB/s eta 0:00:07
   -------------- ------------------------- 13.6/36.6 MB 3.9 MB/s eta 0:00:06
   --------------- ------------------------ 14.4/36.6 MB 3.9 MB/s eta 0:00:06
   ---------------- ----------------------- 15.2/36.6 MB 3.9 MB/s eta 0:00:06
   ----------------- ---------------------- 16.0/36.6 MB 3.9 MB/s eta 0:00:06
   ------------------ --------------------- 16.8/36.6 MB 3.9 MB/s eta 0:00:06
   ------------------- -------------------- 17.6/36.6 MB 3.9 MB/s eta 0:00:05
   -------------------- ------------------- 18.4/36.6 MB 3.9 MB/s eta 0:00:05
   --------------------- ------------------ 19.4/36.6 MB 3.9 MB/s eta 0:00:05
   ---------------------- ----------------- 20.2/36.6 MB 3.9 MB/s eta 0:00:05
   ---------------------- ----------------- 21.0/36.6 MB 3.9 MB/s eta 0:00:05
   ----------------------- ---------------- 21.8/36.6 MB 3.9 MB/s eta 0:00:04
   ------------------------ --------------- 22.5/36.6 MB 3.9 MB/s eta 0:00:04
   ------------------------- -------------- 23.3/36.6 MB 3.9 MB/s eta 0:00:04
   -------------------------- ------------- 24.1/36.6 MB 3.9 MB/s eta 0:00:04
   --------------------------- ------------ 24.9/36.6 MB 3.9 MB/s eta 0:00:03
   ---------------------------- ----------- 25.7/36.6 MB 3.9 MB/s eta 0:00:03
   ---------------------------- ----------- 26.5/36.6 MB 3.9 MB/s eta 0:00:03
   ----------------------------- ---------- 27.3/36.6 MB 3.9 MB/s eta 0:00:03
   ------------------------------ --------- 28.0/36.6 MB 3.9 MB/s eta 0:00:03
   ------------------------------- -------- 28.8/36.6 MB 3.9 MB/s eta 0:00:02
   -------------------------------- ------- 29.6/36.6 MB 3.9 MB/s eta 0:00:02
   --------------------------------- ------ 30.4/36.6 MB 3.9 MB/s eta 0:00:02
   ---------------------------------- ----- 31.2/36.6 MB 3.9 MB/s eta 0:00:02
   ----------------------------------- ---- 32.2/36.6 MB 3.9 MB/s eta 0:00:02
   ------------------------------------ --- 33.0/36.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 33.8/36.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/36.6 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 3.8 MB/s  0:00:09
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   -------------------------------- ------- 4/5 [scikit-learn]
   ---------------------------------------- 5/5 [scikit-learn]

Successfully installed joblib-1.5.3 narwhals-2.23.0 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0
Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Sneh Gurdasani\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn) (2.3.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.18.0-cp313-cp313-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\Sneh Gurdasani\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn) (3.6.0)
Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.23.0-py3-none-any.whl (458 kB)
Using cached scipy-1.18.0-cp313-cp313-win_amd64.whl (36.6 MB)
Installing collected packages: scipy, narwhals, joblib, scikit-learn

   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------------------------------------- 0/4 [scipy]
   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   ---------- ----------------------------- 1/4 [narwhals]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]


In [18]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [19]:
s=StandardScaler()

In [20]:
df[['RUNS']]=s.fit_transform(df[['RUNS']])

In [21]:
m=MinMaxScaler()

In [22]:
df[['SR']]=m.fit_transform(df[['SR']])

In [23]:
df

,Unnamed: 0.1,Unnamed: 0,PLAYER,MATCHES,INNS,RUNS,AVG,SR,4s,6s
0,0,0,Vaibhav Sooryavanshi,16,16,2.012657,48.50,1.000000,63,72
1,1,1,Shubman Gill,16,16,1.529443,45.75,0.124573,74,33
2,2,2,Sai Sudharsan,17,17,1.419622,45.12,0.065174,75,30
3,3,3,Virat Kohli,16,16,0.903462,56.25,0.157808,73,25
4,4,4,Heinrich Klaasen,15,15,0.343374,48.00,0.088863,48,31
5,5,5,Ishan Kishan,15,15,0.101768,40.13,0.353094,60,32
6,6,6,KL Rahul,14,14,0.002929,45.62,0.258692,56,31
7,7,7,Abhishek Sharma,15,15,-0.326535,40.21,0.616028,50,43
8,8,8,Mitchell Marsh,13,13,-0.326535,43.31,0.126458,51,36
9,9,9,Jos Buttler,17,17,-0.732873,37.57,0.000000,51,26
10,10,10,Dhruv Jurel,16,16,-0.853677,36.79,0.025810,47,24
11,11,11,Prabhsimran Singh,14,13,-0.908587,42.50,0.193400,55,23
12,12,12,Rajat Patidar,15,14,-1.007426,41.75,0.474131,30,42
13,13,13,Shreyas Iyer,14,13,-1.040373,55.33,0.192693,39,30
14,14,14,Cooper Connolly,14,13,-1.117248,44.64,0.125633,43,32

In [24]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,MATCHES,INNS,RUNS,AVG,SR,4s,6s
count,15.000000,15.000000,15.000000,15.000000,1.500000e+01,15.000000,15.000000,15.000000,15.000000
mean,7.000000,7.000000,15.133333,14.866667,-1.924387e-16,44.764667,0.253490,54.333333,34.000000
std,4.472136,4.472136,1.187234,1.457330,1.035098e+00,5.629769,0.266132,12.992672,12.005951
min,0.000000,0.000000,13.000000,13.000000,-1.117248e+00,36.790000,0.000000,30.000000,23.000000
25%,3.500000,3.500000,14.000000,13.500000,-8.811321e-01,40.980000,0.106718,47.500000,28.000000
50%,7.000000,7.000000,15.000000,15.000000,-3.265350e-01,44.640000,0.157808,51.000000,31.000000
75%,10.500000,10.500000,16.000000,16.000000,6.234183e-01,46.875000,0.305893,61.500000,34.500000
max,14.000000,14.000000,17.000000,17.000000,2.012657e+00,56.250000,1.000000,75.000000,72.000000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  15 non-null     int64
 1   Unnamed: 0    15 non-null     int64
 2   PLAYER        15 non-null     object
 3   MATCHES       15 non-null     int64
 4   INNS          15 non-null     int64
 5   RUNS          15 non-null     float64
 6   AVG           15 non-null     float64
 7   SR            15 non-null     float64
 8   4s            15 non-null     int64
 9   6s            15 non-null     int64
dtypes: float64(3), int64(6), object(1)
memory usage: 1.3+ KB

In [72]:
df.info()

<class 'pandas.DataFrame'>
Index: 15 entries, 1 to 18
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   PLAYER   15 non-null     str
 1   MATCHES  15 non-null     float64
 2   INNS     15 non-null     int64
 3   RUNS     15 non-null     float64
 4   AVG      15 non-null     float64
 5   SR       15 non-null     float64
 6   4s       15 non-null     float64
 7   6s       15 non-null     float64
dtypes: float64(6), int64(1), str(1)
memory usage: 1.2 KB

In [26]:
df.shape

(15, 10)

In [27]:
df['Team'] = ['A','B','A','A','A','B','B','B','B','A','B','A','A','B','A']

In [28]:
df

,Unnamed: 0.1,Unnamed: 0,PLAYER,MATCHES,INNS,RUNS,AVG,SR,4s,6s,Team
0,0,0,Vaibhav Sooryavanshi,16,16,2.012657,48.50,1.000000,63,72,A
1,1,1,Shubman Gill,16,16,1.529443,45.75,0.124573,74,33,B
2,2,2,Sai Sudharsan,17,17,1.419622,45.12,0.065174,75,30,A
3,3,3,Virat Kohli,16,16,0.903462,56.25,0.157808,73,25,A
4,4,4,Heinrich Klaasen,15,15,0.343374,48.00,0.088863,48,31,A
5,5,5,Ishan Kishan,15,15,0.101768,40.13,0.353094,60,32,B
6,6,6,KL Rahul,14,14,0.002929,45.62,0.258692,56,31,B
7,7,7,Abhishek Sharma,15,15,-0.326535,40.21,0.616028,50,43,B
8,8,8,Mitchell Marsh,13,13,-0.326535,43.31,0.126458,51,36,B
9,9,9,Jos Buttler,17,17,-0.732873,37.57,0.000000,51,26,A
10,10,10,Dhruv Jurel,16,16,-0.853677,36.79,0.025810,47,24,B
11,11,11,Prabhsimran Singh,14,13,-0.908587,42.50,0.193400,55,23,A
12,12,12,Rajat Patidar,15,14,-1.007426,41.75,0.474131,30,42,A
13,13,13,Shreyas Iyer,14,13,-1.040373,55.33,0.192693,39,30,B
14,14,14,Cooper Connolly,14,13,-1.117248,44.64,0.125633,43,32,A

In [29]:
a=df.groupby('Team')

In [30]:
a.sum()['6s']

Team
A    281
B    229
Name: 6s, dtype: int64

In [31]:
a.max()

,Unnamed: 0.1,Unnamed: 0,PLAYER,MATCHES,INNS,RUNS,AVG,SR,4s,6s
Team,,,,,,,,,,
A,14,14,Virat Kohli,17,17,2.012657,56.25,1.000000,75,72
B,13,13,Shubman Gill,16,16,1.529443,55.33,0.616028,74,43

In [32]:
a.count()['PLAYER']

Team
A    8
B    7
Name: PLAYER, dtype: int64

In [33]:
df=pd.read_excel('C:/Users/PC/Desktop/Products.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/PC/Desktop/Products.xlsx'

In [ ]:
df1=df.copy()

In [ ]:
df

In [ ]:
pd.crosstab(df['Category'],[df['Country'],df['Quality']])

       Category Quality Country
0   Electronics       A   India
1   Electronics       D   China
2   Electronics       A   India
3     Household       B   South
4     Household       C   China
5     Household       B   South
6   Electronics       B   India
7      Footwear       A  Russia
8      Footwear       B   China
9      Footwear       A  Russia
10     Footwear       B  Russia
11  Electronics       B   India

In [ ]:
df

Country     China       India    Russia    South
Quality         B  C  D     A  B      A  B     B
Category
Electronics     0  0  1     2  2      0  0     0
Footwear        1  0  0     0  0      2  1     0
Household       0  1  0     0  0      0  0     2

In [34]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [36]:
l=LabelEncoder()

In [37]:
df['Quality'].unique()

KeyError: 'Quality'

In [ ]:
df['Quality'].nunique()

<ArrowStringArray>
['A', 'D', 'B', 'C']
Length: 4, dtype: str

In [ ]:
df['Quality'].value_counts()

4

In [ ]:
df['Quality_nums']=l.fit_transform(df['Quality'])

Quality
B    6
A    4
D    1
C    1
Name: count, dtype: int64

In [ ]:
on=OneHotEncoder()

In [ ]:
v=on.fit_transform(df[['Quality']])

In [38]:
df[['A','B','C','D']]=v.toarray()

NameError: name 'v' is not defined

In [ ]:
df

In [ ]:
df[df['Quality_nums']==1]

       Category Quality Country    A    B    C    D  Quality_nums
0   Electronics       A   India  1.0  0.0  0.0  0.0             0
1   Electronics       D   China  0.0  0.0  0.0  1.0             3
2   Electronics       A   India  1.0  0.0  0.0  0.0             0
3     Household       B   South  0.0  1.0  0.0  0.0             1
4     Household       C   China  0.0  0.0  1.0  0.0             2
5     Household       B   South  0.0  1.0  0.0  0.0             1
6   Electronics       B   India  0.0  1.0  0.0  0.0             1
7      Footwear       A  Russia  1.0  0.0  0.0  0.0             0
8      Footwear       B   China  0.0  1.0  0.0  0.0             1
9      Footwear       A  Russia  1.0  0.0  0.0  0.0             0
10     Footwear       B  Russia  0.0  1.0  0.0  0.0             1
11  Electronics       B   India  0.0  1.0  0.0  0.0             1