structure data - table data , labeled data

In [ ]:
#pip install pandas

In [1]:
import pandas as pd

In [2]:
pwd

'c:\\Users\\Sneh Gurdasani\\Downloads'

In [5]:
df = pd.read_csv("C:\\Users\\Sneh Gurdasani\\Downloads\\Iris.csv")

In [6]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [7]:
df.head(2)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa

In [8]:
df.tail(2)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [9]:
df.tail(2)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [11]:
df.SepalLengthCm

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [12]:
length = df['SepalLengthCm']

In [13]:
length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [14]:
type(length)

pandas.core.series.Series

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.shape

(150, 6)

In [17]:
data = df[["SepalWidthCm", "PetalWidthCm", "Species"]]

In [18]:
data.to_excel("Flowers.xlsx")

In [ ]:
data.to_excel('Flowers.xlsx')

In [19]:
d = pd.read_excel('Flowers.xlsx')
d.head()

   Unnamed: 0  SepalWidthCm  PetalWidthCm      Species
0           0           3.5           0.2  Iris-setosa
1           1           3.0           0.2  Iris-setosa
2           2           3.2           0.2  Iris-setosa
3           3           3.1           0.2  Iris-setosa
4           4           3.6           0.2  Iris-setosa

In [22]:
!pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Collecting lxml
  Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 1.0 MB/s eta 0:00:04
   ------- -------------------------------- 0.8/4.0 MB 1.1 MB/s eta 0:00:04
   ---------- ----------------------------- 1.0/4.0 MB 1.2 MB/s eta 0:00:03
   ------------- -------------------------- 1.3/4.0 MB 1.2 MB/s eta 0:00:03
   --------------- ------------------------ 1.6/4.0 MB 1.3 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.4 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.4 MB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 1.5 MB/s eta 0:00:01
   ---------------------------------- ----- 3.4/4.0 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 1.7 MB/s  0:00:02
Installing collected packages: lxml
Successfully installed lxml-6.1.1

WARNING: Cache entry deserialization failed, entry ignored

In [24]:
df2 = pd.read_html("https://www.cricbuzz.com/cricket-series/9241/indian-premier-league-2026/stats")

In [26]:
df2[0]

                  PLAYER  MATCHES  INNS  RUNS    AVG      SR  4s  6s
0   Vaibhav Sooryavanshi       16    16   776  48.50  237.31  63  72
1           Shubman Gill       16    16   732  45.75  163.03  74  33
2          Sai Sudharsan       17    17   722  45.12  157.99  75  30
3            Virat Kohli       16    16   675  56.25  165.85  73  25
4       Heinrich Klaasen       15    15   624  48.00  160.00  48  31
5           Ishan Kishan       15    15   602  40.13  182.42  60  32
6               KL Rahul       14    14   593  45.62  174.41  56  31
7        Abhishek Sharma       15    15   563  40.21  204.73  50  43
8         Mitchell Marsh       13    13   563  43.31  163.19  51  36
9            Jos Buttler       17    17   526  37.57  152.46  51  26
10           Dhruv Jurel       16    16   515  36.79  154.65  47  24
11     Prabhsimran Singh       14    13   510  42.50  168.87  55  23
12         Rajat Patidar       15    14   501  41.75  192.69  30  42
13          Shreyas Iyer       14    13   498  55.33  168.81  39  30
14       Cooper Connolly       14    13   491  44.64  163.12  43  32

In [27]:
df.to_csv("match_stats.csv")

In [47]:
df.to_csv('match_stats.csv')

In [37]:
!pip uninstall mysql-connector

^C

In [33]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   -- ------------------------------------- 1.0/17.7 MB 3.9 MB/s eta 0:00:05
   --- ------------------------------------ 1.6/17.7 MB 4.5 MB/s eta 0:00:04
   ---- ----------------------------------- 2.1/17.7 MB 3.1 MB/s eta 0:00:06
   ----- ---------------------------------- 2.4/17.7 MB 2.6 MB/s eta 0:00:06
   ----- ---------------------------------- 2.6/17.7 MB 2.3 MB/s eta 0:00:07
   -------- ------------------------------- 3.7/17.7 MB 2.7 MB/s eta 0:00:06
   ---------- ----------------------------- 4.7/17.7 MB 3.0 MB/s eta 0:00:05
   ------------ --------------------------- 5.5/17.7 MB 3.1 MB/s eta 0:00:04
   ------------- -------------------------- 6.0/17.7 MB 3.2 MB/s eta 0:00:04
   ---------------- ----------------------- 7.1/17.7 MB 3.3 MB/s eta 0:00:04
   ----------------- ---------------------- 7.9/17.7 MB 3.3 MB/s eta 0:00:03
   ------------------- -------------------- 8.7/17.7 MB 3.4 MB/s eta 0:00:03
   --------------------- ------------------ 9.4/17.7 MB 3.4 MB/s eta 0:00:03
   ----------------------- ---------------- 10.2/17.7 MB 3.5 MB/s eta 0:00:03
   ------------------------- -------------- 11.3/17.7 MB 3.5 MB/s eta 0:00:02
   --------------------------- ------------ 12.1/17.7 MB 3.5 MB/s eta 0:00:02
   ----------------------------- ---------- 12.8/17.7 MB 3.5 MB/s eta 0:00:02
   ------------------------------ --------- 13.6/17.7 MB 3.6 MB/s eta 0:00:02
   -------------------------------- ------- 14.4/17.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------- ----- 15.2/17.7 MB 3.6 MB/s eta 0:00:01
   ------------------------------------ --- 16.0/17.7 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 16.8/17.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 3.5 MB/s  0:00:05
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

WARNING: Cache entry deserialization failed, entry ignored

In [44]:
import mysql.connector

In [46]:
con = mysql.connector.connect(user='root', password='root', host='localhost', db='institute', auth_plugin='mysql_native_password')

In [47]:
pd.read_sql('select * from employees',con)

C:\Users\Sneh Gurdasani\AppData\Local\Temp\ipykernel_25548\1969616969.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('select * from employees',con)

   id first_name last_name
0   1        tim      sehn
1   2      aaron       son
2   3      brian  hendriks

In [48]:
df

                  PLAYER  MATCHES  INNS  RUNS    AVG      SR  4s  6s
0   Vaibhav Sooryavanshi       16    16   776  48.50  237.31  63  72
1           Shubman Gill       16    16   732  45.75  163.03  74  33
2          Sai Sudharsan       17    17   722  45.12  157.99  75  30
3            Virat Kohli       16    16   675  56.25  165.85  73  25
4       Heinrich Klaasen       15    15   624  48.00  160.00  48  31
5           Ishan Kishan       15    15   602  40.13  182.42  60  32
6               KL Rahul       14    14   593  45.62  174.41  56  31
7        Abhishek Sharma       15    15   563  40.21  204.73  50  43
8         Mitchell Marsh       13    13   563  43.31  163.19  51  36
9            Jos Buttler       17    17   526  37.57  152.46  51  26
10           Dhruv Jurel       16    16   515  36.79  154.65  47  24
11     Prabhsimran Singh       14    13   510  42.50  168.87  55  23
12         Rajat Patidar       15    14   501  41.75  192.69  30  42
13          Shreyas Iyer       14    13   498  55.33  168.81  39  30
14       Cooper Connolly       14    13   491  44.64  163.12  43  32

In [49]:
df.head(3)

                 PLAYER  MATCHES  INNS  RUNS    AVG      SR  4s  6s
0  Vaibhav Sooryavanshi       16    16   776  48.50  237.31  63  72
1          Shubman Gill       16    16   732  45.75  163.03  74  33
2         Sai Sudharsan       17    17   722  45.12  157.99  75  30

In [50]:
df.tail(3)

             PLAYER  MATCHES  INNS  RUNS    AVG      SR  4s  6s
12    Rajat Patidar       15    14   501  41.75  192.69  30  42
13     Shreyas Iyer       14    13   498  55.33  168.81  39  30
14  Cooper Connolly       14    13   491  44.64  163.12  43  32

In [51]:
df['RUNS']

0     776
1     732
2     722
3     675
4     624
5     602
6     593
7     563
8     563
9     526
10    515
11    510
12    501
13    498
14    491
Name: RUNS, dtype: int64

In [53]:
df.at[4,'AVG']

np.float64(48.0)

In [57]:
df.at[4,'AVG']  #cell by labels

np.float64(48.0)

In [54]:
df.iat[3,5]

np.float64(165.85)

In [55]:
df.loc[2,['PLAYER','MATCHES','RUNS']]

PLAYER     Sai Sudharsan
MATCHES               17
RUNS                 722
Name: 2, dtype: object

In [56]:
df.loc[[2,3,4],['PLAYER','MATCHES','RUNS']]

             PLAYER  MATCHES  RUNS
2     Sai Sudharsan       17   722
3       Virat Kohli       16   675
4  Heinrich Klaasen       15   624

In [57]:
df.iloc[3:6,1:6]

   MATCHES  INNS  RUNS    AVG      SR
3       16    16   675  56.25  165.85
4       15    15   624  48.00  160.00
5       15    15   602  40.13  182.42

In [58]:
import numpy as np

In [59]:
a = np.array([3,5,2,4,6,3,4,5,4,2,4,3,5])
pd.Series(a, index=list('abcdefghijklm'))

a    3
b    5
c    2
d    4
e    6
f    3
g    4
h    5
i    4
j    2
k    4
l    3
m    5
dtype: int64

In [60]:
b = np.arange(11,35).reshape(6,4)
b

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34]])

In [61]:
pd.DataFrame(b,columns=['A','B','C','D'],index=['a1','a2','a3','a4','a5','a6'])

     A   B   C   D
a1  11  12  13  14
a2  15  16  17  18
a3  19  20  21  22
a4  23  24  25  26
a5  27  28  29  30
a6  31  32  33  34

In [62]:
df['RUNS'].values

array([776, 732, 722, 675, 624, 602, 593, 563, 563, 526, 515, 510, 501,
       498, 491])

In [63]:
df.values

array([['Vaibhav Sooryavanshi', 16, 16, 776, 48.5, 237.31, 63, 72],
       ['Shubman Gill', 16, 16, 732, 45.75, 163.03, 74, 33],
       ['Sai Sudharsan', 17, 17, 722, 45.12, 157.99, 75, 30],
       ['Virat Kohli', 16, 16, 675, 56.25, 165.85, 73, 25],
       ['Heinrich Klaasen', 15, 15, 624, 48.0, 160.0, 48, 31],
       ['Ishan Kishan', 15, 15, 602, 40.13, 182.42, 60, 32],
       ['KL Rahul', 14, 14, 593, 45.62, 174.41, 56, 31],
       ['Abhishek Sharma', 15, 15, 563, 40.21, 204.73, 50, 43],
       ['Mitchell Marsh', 13, 13, 563, 43.31, 163.19, 51, 36],
       ['Jos Buttler', 17, 17, 526, 37.57, 152.46, 51, 26],
       ['Dhruv Jurel', 16, 16, 515, 36.79, 154.65, 47, 24],
       ['Prabhsimran Singh', 14, 13, 510, 42.5, 168.87, 55, 23],
       ['Rajat Patidar', 15, 14, 501, 41.75, 192.69, 30, 42],
       ['Shreyas Iyer', 14, 13, 498, 55.33, 168.81, 39, 30],
       ['Cooper Connolly', 14, 13, 491, 44.64, 163.12, 43, 32]],
      dtype=object)

In [64]:
sales = {'Emps':['Amit','Sumit','Deepak','Rohit','Mohit'],
         'Sales':[23456,54321,34323,43534,34563],
         'Comp':['Google','Amazon','Google','Flipkart','Amazon']
         }

In [65]:
pd.DataFrame(sales)

     Emps  Sales      Comp
0    Amit  23456    Google
1   Sumit  54321    Amazon
2  Deepak  34323    Google
3   Rohit  43534  Flipkart
4   Mohit  34563    Amazon

In [66]:
import requests

In [67]:
res = requests.get('https://fakestoreapi.com/products')

In [69]:
data = res.json()

In [70]:
data

[{'id': 1,
  'title': 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
  'price': 109.95,
  'description': 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
  'category': "men's clothing",
  'image': 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png',
  'rating': {'rate': 3.9, 'count': 120}},
 {'id': 2,
  'title': 'Mens Casual Premium Slim Fit T-Shirts ',
  'price': 22.3,
  'description': 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.',
  'category': "men's clothing",
  'image': 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png',
  'rating': {'rate': 4.1, 'count': 259}},
 {'id': 3,
  'title': 'Mens Cotton Jacket',
  'price': 55.99,
  'description': 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.',
  'category': "men's clothing",
  'image': 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png',
  'rating': {'rate': 4.7, 'count': 500}},
 {'id': 4,
  'title': 'Mens Casual Slim Fit',
  'price': 15.99,
  'description': 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.',
  'category': "men's clothing",
  'image': 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png',
  'rating': {'rate': 2.1, 'count': 430}},
 {'id': 5,
  'title': "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
  'price': 695,
  'description': "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
  'category': 'jewelery',
  'image': 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png',
  'rating': {'rate': 4.6, 'count': 400}},
 {'id': 6,
  'title': 'Solid Gold Petite Micropave ',
  'price': 168,
  'description': 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.',
  'category': 'jewelery',
  'image': 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png',
  'rating': {'rate': 3.9, 'count': 70}},
 {'id': 7,
  'title': 'White Gold Plated Princess',
  'price': 9.99,
  'description': "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
  'category': 'jewelery',
  'image': 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png',
  'rating': {'rate': 3, 'count': 400}},
 {'id': 8,
  'title': 'Pierced Owl Rose Gold Plated Stainless Steel Double',
  'price': 10.99,
  'description': 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel',
  'category': 'jewelery',
  'image': 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png',
  'rating': {'rate': 1.9, 'count': 100}},
 {'id': 9,
  'title': 'WD 2TB Elements Portable External Hard Drive - USB 3.0 ',
  'price': 64,
  'description': 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system',
  'category': 'electronics',
  'image': 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png',
  'rating': {'rate': 3.3, 'count': 203}},
 {'id': 10,
  'title': 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',
  'price': 109,
  'description': 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)',
  'category': 'electronics',
  'image': 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png',
  'rating': {'rate': 2.9, 'count': 470}},
 {'id': 11,
  'title': 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',
  'price': 109,
  'description': '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.',
  'category': 'electronics',
  'image': 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png',
  'rating': {'rate': 4.8, 'count': 319}},
 {'id': 12,
  'title': 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive',
  'price': 114,
  'description': "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
  'category': 'electronics',
  'image': 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png',
  'rating': {'rate': 4.8, 'count': 400}},
 {'id': 13,
  'title': 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin',
  'price': 599,
  'description': '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz',
  'category': 'electronics',
  'image': 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png',
  'rating': {'rate': 2.9, 'count': 250}},
 {'id': 14,
  'title': 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ',
  'price': 999.99,
  'description': '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag',
  'category': 'electronics',
  'image': 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png',
  'rating': {'rate': 2.2, 'count': 140}},
 {'id': 15,
  'title': "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
  'price': 56.99,
  'description': 'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',
  'category': "women's clothing",
  'image': 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png',
  'rating': {'rate': 2.6, 'count': 235}},
 {'id': 16,
  'title': "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
  'price': 29.95,
  'description': '100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON',
  'category': "women's clothing",
  'image': 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png',
  'rating': {'rate': 2.9, 'count': 340}},
 {'id': 17,
  'title': 'Rain Jacket Women Windbreaker Striped Climbing Raincoats',
  'price': 39.99,
  'description': "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
  'category': "women's clothing",
  'image': 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png',
  'rating': {'rate': 3.8, 'count': 679}},
 {'id': 18,
  'title': "MBJ Women's Solid Short Sleeve Boat Neck V ",
  'price': 9.85,
  'description': '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem',
  'category': "women's clothing",
  'image': 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png',
  'rating': {'rate': 4.7, 'count': 130}},
 {'id': 19,
  'title': "Opna Women's Short Sleeve Moisture",
  'price': 7.95,
  'description': '100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort',
  'category': "women's clothing",
  'image': 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png',
  'rating': {'rate': 4.5, 'count': 146}},
 {'id': 20,
  'title': 'DANVOUY Womens T Shirt Casual Cotton Short',
  'price': 12.99,
  'description': '95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.',
  'category': "women's clothing",
  'image': 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png',
  'rating': {'rate': 3.6, 'count': 145}}]

In [71]:
d1 = pd.DataFrame(data)

In [72]:
d1.to_csv('Products.csv')