In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
os.getcwd()

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Bihar_Election_Results.csv")

In [ ]:
df.head()

,Election Year,Position,Name,Votes,Votes %,Party,AC name,AC No
0,2010,1,Rajesh Singh,42289,29.40%,Janata Dal (United),Valmiki Nagar,1
1,2010,2,Mukesh Kumar Kushwaha,27618,19.20%,Rashtriya Janata Dal,Valmiki Nagar,1
2,2010,3,Dheerendra Pratap Singh,20886,14.50%,Bahujan Samaj Party,Valmiki Nagar,1
3,2010,4,Irshad Hussain,17747,12.40%,Indian National Congress,Valmiki Nagar,1
4,2010,5,Deep Narayan Mahato,14047,9.80%,Independent,Valmiki Nagar,1

In [ ]:
df.columns

Index(['Election Year', 'Position', 'Name', 'Votes', 'Votes %', 'Party',
       'AC name', 'AC No'],
      dtype='object')

In [ ]:
df['Election Year'].unique()

array(['2010', '2015', '2005-Oct', '2005-Feb'], dtype=object)

In [11]:
# 1st question
# Determine the winning party for every election at the state level. A party which
# has the highest total votes is considered the winner here.
feb_2005_df = df.loc[df['Election Year']=='2005-Feb']
print("Feb 2005 elections winner: ",feb_2005_df.groupby(by=['Party'])['Votes'].sum().idxmax()," votes: ", feb_2005_df.groupby(by=['Party'])['Votes'].sum().max())
oct_2005_df = df.loc[df['Election Year']=='2005-Oct']
print("Oct 2005 elections winner: ",oct_2005_df.groupby(by=['Party'])['Votes'].sum().idxmax()," votes: ", oct_2005_df.groupby(by=['Party'])['Votes'].sum().max())
# print(oct_2005_df.groupby(by=['Party'])['Votes'].sum())
df_2010 = df.loc[df['Election Year']=='2010']
print("2010 elections winner: ",df_2010.groupby(by=['Party'])['Votes'].sum().idxmax()," votes: ", df_2010.groupby(by=['Party'])['Votes'].sum().max())
# print(df_2010.groupby(by=['Party'])['Votes'].sum())
df_2015 = df.loc[df['Election Year']=='2015']
print("2015 elections winner: ",df_2015.groupby(by=['Party'])['Votes'].sum().idxmax()," votes: ", df_2015.groupby(by=['Party'])['Votes'].sum().max())
# print(df_2015.groupby(by=['Party'])['Votes'].sum())
# idx = df.groupby(by=['Election Year','Party'])['Votes'].sum()
# winning_party = df.loc[idx]
# winning_party

Feb 2005 elections winner:  Rashtriya Janata Dal  votes:  6140223
Oct 2005 elections winner:  Rashtriya Janata Dal  votes:  5525081
2010 elections winner:  Janata Dal (United)  votes:  6561906
2015 elections winner:  Bharatiya Janta Party  votes:  9308015

In [ ]:
# 2nd question
ac_no_list = df['AC No'].unique()
election_year_list = df['Election Year'].unique()
swing_seat = 0
for ac_no in ac_no_list:
  party_list = []
  for election_year in election_year_list:
    if not df.loc[(df['AC No']==ac_no) & (df['Election Year'] == election_year)].empty:
      idx = df.loc[(df['AC No']==ac_no) & (df['Election Year'] == election_year)]['Votes'].idxmax()
      party_list.append(df.loc[idx]['Party'])
  print(len(party_list))
  if party_list:
    if len(party_list) == 4:
      if party_list[0] != party_list[1] and party_list[0] != party_list[2] and party_list[0] != party_list[3]:
        swing_seat += 1
print("Swing seats: ",swing_seat)

4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
1
1
98

In [ ]:
#3rd question Determine the top 8 parties at the state-level in each election in terms of getting
# the most votes.
party_unique_list = df['Party'].unique()
election_year_list = df['Election Year'].unique()
party_election_year_votes_df = pd.DataFrame(columns=['Party','Election Year','Votes_sum'])
output_df = party_election_year_votes_df.copy()
for election_year in election_year_list:
  for party in party_unique_list:
    party_election_year_votes_sum = df.loc[(df['Election Year'] == election_year) & (df['Party']==party)]['Votes'].sum()
    new_row = pd.DataFrame({'Party':party,'Election Year':election_year,'Votes_sum':party_election_year_votes_sum},index=[0])
    party_election_year_votes_df = pd.concat([party_election_year_votes_df, new_row],ignore_index=True)

party_election_year_votes_df_sorted = party_election_year_votes_df.sort_values(by=['Election Year','Votes_sum'],ascending=False)
for election_year in election_year_list:
   for i in range(8):
    idx = party_election_year_votes_df_sorted.loc[party_election_year_votes_df_sorted['Election Year']==election_year]['Votes_sum'].idxmax()
    new_row = pd.DataFrame({'Party':party_election_year_votes_df_sorted.loc[idx,'Party'],'Election Year':party_election_year_votes_df_sorted.loc[idx,'Election Year'], 'Votes_sum':party_election_year_votes_df_sorted.loc[idx,'Votes_sum']}, index=[0])
    output_df = pd.concat([output_df,new_row],ignore_index=True)
    party_election_year_votes_df_sorted = party_election_year_votes_df_sorted.drop(idx)
output_df

                               Party Election Year Votes_sum
0                Janata Dal (United)          2010   6561906
1               Rashtriya Janata Dal          2010   5475656
2              Bharatiya Janta Party          2010   4790436
3                        Independent          2010   3842812
4           Indian National Congress          2010   2431477
5               Lok Jan Shakti Party          2010   1957232
6                Bahujan Samaj Party          2010    933947
7         Nationalist Congress Party          2010    528575
8              Bharatiya Janta Party          2015   9308015
9               Rashtriya Janata Dal          2015   6995509
10               Janata Dal (United)          2015   6416414
11                       Independent          2015   3580953
12          Indian National Congress          2015   2539638
13              Lok Jan Shakti Party          2015   1840834
14         Rashtriya Lok Samta Party          2015    976787
15  Hindustani Awam Morcha (Secular)          2015    864856
16              Rashtriya Janata Dal      2005-Oct   5525081
17               Janata Dal (United)      2005-Oct   4819759
18             Bharatiya Janta Party      2005-Oct   3686720
19              Lok Jan Shakti Party      2005-Oct   2615901
20                       Independent      2005-Oct   2065744
21          Indian National Congress      2005-Oct   1435449
22               Bahujan Samaj Party      2005-Oct    981464
23                   Samajwadi Party      2005-Oct    594266
24              Rashtriya Janata Dal      2005-Feb   6140223
25                       Independent      2005-Feb   3957945
26               Janata Dal (United)      2005-Feb   3564930
27              Lok Jan Shakti Party      2005-Feb   3091173
28             Bharatiya Janta Party      2005-Feb   2686290
29          Indian National Congress      2005-Feb   1223835
30               Bahujan Samaj Party      2005-Feb   1080745
31                   Samajwadi Party      2005-Feb    658791

In [ ]:
#4th question
# Determine the minimum votes that each party in the top 8 of the 2015 election
# secured among all the past elections. Do this for all constituencies.
party_list = output_df.loc[(output_df['Election Year']=='2015')]
output_4th_df = pd.DataFrame(columns=['Party','Election Year','Min_Votes'])
for party in party_list['Party']:
  idx = df.loc[(df['Party']==party) & (df['Election Year']=='2015')]['Votes'].idxmin()
  new_row = pd.DataFrame({'Party':df.loc[idx,'Party'],'Election Year':df.loc[idx,'Election Year'], 'Min_Votes':df.loc[idx,'Votes']}, index=[0])
  output_4th_df = pd.concat([output_4th_df,new_row],ignore_index=True)
output_4th_df

Bharatiya Janta Party
Rashtriya Janata Dal
Janata Dal (United)
Independent
Indian National Congress
Lok Jan Shakti Party
Rashtriya Lok Samta Party
Hindustani Awam Morcha (Secular)

                              Party Election Year Min_Votes
0             Bharatiya Janta Party          2015     18496
1              Rashtriya Janata Dal          2015     37345
2               Janata Dal (United)          2015     30287
3                       Independent          2015       143
4          Indian National Congress          2015     29558
5              Lok Jan Shakti Party          2015      7383
6         Rashtriya Lok Samta Party          2015      9573
7  Hindustani Awam Morcha (Secular)          2015      4206

In [16]:
from decimal import Decimal

In [17]:
df['Votes %'] = df['Votes %'].apply(lambda x:Decimal(x.replace("%","")))
# clean_text = text.translate(str.maketrans("", "", string.punctuation))
print(df['Votes %'])
# df.loc[:,'Votes %'] = df.loc[:,'Votes %'].split()

0        29.40
1        19.20
2        14.50
3        12.40
4         9.80
         ...
12296     0.60
12297     0.60
12298     0.50
12299     0.50
12300     0.50
Name: Votes %, Length: 12301, dtype: object

In [ ]:
df.columns

Index(['Election Year', 'Position', 'Name', 'Votes', 'Votes %', 'Party',
       'AC name', 'AC No'],
      dtype='object')

In [ ]:
# 5th question : Determine the consistently tri-polar constituencies. I.e Constituencies in which 3
# parties or more got greater than 10% of the vote shares in each election. The
# parties can be different for different elections.
ac_no_list = df['AC No'].unique()
election_year_list = df['Election Year'].unique()
party_unique_list = df['Party'].unique()
output_5th_df = pd.DataFrame(columns=['AC No','AC name','Election Year'])
for ac_no in ac_no_list:
    for election_year in election_year_list:
      party_count = 0
      for party in party_unique_list:
        if not df.loc[(df['AC No']==ac_no)&(df['Party']==party)&(df['Election Year']==election_year)]['Votes %'].empty:
          # print("AC No: ", ac_no, "Party: ", party, "Election year: ", election_year, "Total Votes % Sum: ", df.loc[(df['AC No']==ac_no)&(df['Party']==party)&(df['Election Year']==election_year)]['Votes %'].sum())
          if df.loc[(df['AC No']==ac_no)&(df['Party']==party)&(df['Election Year']==election_year)]['Votes %'].sum() > 10.00:
            party_count += 1
      if party_count >= 3:
        print('AC No: ', ac_no,'AC name: ', df.loc[df['AC No']==ac_no]['AC name'].unique()[0], 'Election Year: ', election_year)
        new_row = pd.DataFrame({'AC No':ac_no,'AC name':df.loc[df['AC No']==ac_no]['AC name'].unique()[0],'Election Year':election_year},index=[0])
        output_5th_df = pd.concat([output_5th_df,new_row],ignore_index=True)
output_5th_df

AC No:  1 AC name:  Valmiki Nagar Election Year:  2010
AC No:  1 AC name:  Valmiki Nagar Election Year:  2015
AC No:  1 AC name:  Valmiki Nagar Election Year:  2005-Oct
AC No:  1 AC name:  Valmiki Nagar Election Year:  2005-Feb
AC No:  2 AC name:  Ramnagar Election Year:  2010
AC No:  2 AC name:  Ramnagar Election Year:  2005-Feb
AC No:  3 AC name:  Narkatiaganj Election Year:  2010
AC No:  3 AC name:  Narkatiaganj Election Year:  2015
AC No:  3 AC name:  Narkatiaganj Election Year:  2005-Oct
AC No:  3 AC name:  Narkatiaganj Election Year:  2005-Feb
AC No:  4 AC name:  Bagaha Election Year:  2010
AC No:  4 AC name:  Bagaha Election Year:  2005-Feb
AC No:  5 AC name:  Lauriya Election Year:  2010
AC No:  5 AC name:  Lauriya Election Year:  2015
AC No:  5 AC name:  Lauriya Election Year:  2005-Oct
AC No:  5 AC name:  Lauriya Election Year:  2005-Feb
AC No:  6 AC name:  Nautan Election Year:  2010
AC No:  6 AC name:  Nautan Election Year:  2005-Oct
AC No:  6 AC name:  Nautan Election Year:  2005-Feb
AC No:  7 AC name:  Chanpatia Election Year:  2010
AC No:  7 AC name:  Chanpatia Election Year:  2005-Oct
AC No:  7 AC name:  Chanpatia Election Year:  2005-Feb
AC No:  8 AC name:  Bettiah Election Year:  2010
AC No:  8 AC name:  Bettiah Election Year:  2015
AC No:  9 AC name:  Sikta Election Year:  2005-Oct
AC No:  9 AC name:  Sikta Election Year:  2005-Feb
AC No:  10 AC name:  Raxaul Election Year:  2015
AC No:  10 AC name:  Raxaul Election Year:  2005-Oct
AC No:  10 AC name:  Raxaul Election Year:  2005-Feb
AC No:  11 AC name:  Sugauli Election Year:  2010
AC No:  11 AC name:  Sugauli Election Year:  2015
AC No:  11 AC name:  Sugauli Election Year:  2005-Oct
AC No:  11 AC name:  Sugauli Election Year:  2005-Feb
AC No:  12 AC name:  Narkatia Election Year:  2010
AC No:  12 AC name:  Narkatia Election Year:  2015
AC No:  12 AC name:  Narkatia Election Year:  2005-Oct
AC No:  12 AC name:  Narkatia Election Year:  2005-Feb
AC No:  13 AC name:  Harsidhi Election Year:  2010
AC No:  13 AC name:  Harsidhi Election Year:  2005-Oct
AC No:  13 AC name:  Harsidhi Election Year:  2005-Feb
AC No:  14 AC name:  Govindganj Election Year:  2010
AC No:  14 AC name:  Govindganj Election Year:  2005-Oct
AC No:  14 AC name:  Govindganj Election Year:  2005-Feb
AC No:  15 AC name:  Kesaria Election Year:  2010
AC No:  15 AC name:  Kesaria Election Year:  2005-Oct
AC No:  15 AC name:  Kesaria Election Year:  2005-Feb
AC No:  16 AC name:  Kalyanpur Election Year:  2010
AC No:  16 AC name:  Kalyanpur Election Year:  2015
AC No:  16 AC name:  Kalyanpur Election Year:  2005-Oct
AC No:  16 AC name:  Kalyanpur Election Year:  2005-Feb
AC No:  17 AC name:  Pipra Election Year:  2010
AC No:  17 AC name:  Pipra Election Year:  2015
AC No:  17 AC name:  Pipra Election Year:  2005-Feb
AC No:  18 AC name:  Madhuban Election Year:  2010
AC No:  18 AC name:  Madhuban Election Year:  2005-Oct
AC No:  18 AC name:  Madhuban Election Year:  2005-Feb
AC No:  19 AC name:  Motihari Election Year:  2010
AC No:  19 AC name:  Motihari Election Year:  2005-Oct
AC No:  19 AC name:  Motihari Election Year:  2005-Feb
AC No:  20 AC name:  Chiraia Election Year:  2010
AC No:  20 AC name:  Chiraia Election Year:  2005-Oct
AC No:  20 AC name:  Chiraia Election Year:  2005-Feb
AC No:  21 AC name:  Dhaka Election Year:  2010
AC No:  21 AC name:  Dhaka Election Year:  2015
AC No:  21 AC name:  Dhaka Election Year:  2005-Oct
AC No:  22 AC name:  Sheohar Election Year:  2010
AC No:  22 AC name:  Sheohar Election Year:  2015
AC No:  22 AC name:  Sheohar Election Year:  2005-Oct
AC No:  22 AC name:  Sheohar Election Year:  2005-Feb
AC No:  23 AC name:  Riga Election Year:  2010
AC No:  23 AC name:  Riga Election Year:  2005-Oct
AC No:  23 AC name:  Riga Election Year:  2005-Feb
AC No:  24 AC name:  Bathnaha Election Year:  2005-Oct
AC No:  24 AC name:  Bathnaha Election Year:  2005-Feb
AC No:  25 AC name:  Parihar Election Year:  2010
AC No:  25 AC name:  Parihar Election Year:  2005-Oct
AC No:  25 AC name:  Parihar Election Year:  2005-Feb
AC No:  26 AC name:  Sursand Election Year:  2010
AC No:  26 AC name:  Sursand Election Year:  2005-Feb
AC No:  27 AC name:  Bajpatti Election Year:  2010
AC No:  27 AC name:  Bajpatti Election Year:  2015
AC No:  28 AC name:  Sitamarhi Election Year:  2005-Feb
AC No:  29 AC name:  Runisaidpur Election Year:  2010
AC No:  29 AC name:  Runisaidpur Election Year:  2015
AC No:  29 AC name:  Runisaidpur Election Year:  2005-Feb
AC No:  30 AC name:  Belsand Election Year:  2010
AC No:  30 AC name:  Belsand Election Year:  2005-Oct
AC No:  30 AC name:  Belsand Election Year:  2005-Feb
AC No:  31 AC name:  Harlakhi Election Year:  2010
AC No:  31 AC name:  Harlakhi Election Year:  2015
AC No:  31 AC name:  Harlakhi Election Year:  2005-Oct
AC No:  31 AC name:  Harlakhi Election Year:  2005-Feb
AC No:  32 AC name:  Benipatti Election Year:  2010
AC No:  32 AC name:  Benipatti Election Year:  2015
AC No:  33 AC name:  Khajauli Election Year:  2010
AC No:  34 AC name:  Babubarhi Election Year:  2015
AC No:  34 AC name:  Babubarhi Election Year:  2005-Oct
AC No:  35 AC name:  Bisfi Election Year:  2005-Feb
AC No:  36 AC name:  Madhubani Election Year:  2010
AC No:  36 AC name:  Madhubani Election Year:  2005-Oct
AC No:  36 AC name:  Madhubani Election Year:  2005-Feb
AC No:  37 AC name:  Rajnagar Election Year:  2010
AC No:  37 AC name:  Rajnagar Election Year:  2005-Oct
AC No:  38 AC name:  Jhanjharpur Election Year:  2015
AC No:  38 AC name:  Jhanjharpur Election Year:  2005-Oct
AC No:  38 AC name:  Jhanjharpur Election Year:  2005-Feb
AC No:  39 AC name:  Phulparas Election Year:  2010
AC No:  39 AC name:  Phulparas Election Year:  2005-Oct
AC No:  39 AC name:  Phulparas Election Year:  2005-Feb
AC No:  40 AC name:  Laukaha Election Year:  2010
AC No:  40 AC name:  Laukaha Election Year:  2005-Feb
AC No:  41 AC name:  Nirmali Election Year:  2010
AC No:  41 AC name:  Nirmali Election Year:  2005-Oct
AC No:  41 AC name:  Nirmali Election Year:  2005-Feb
AC No:  43 AC name:  Supaul Election Year:  2010
AC No:  45 AC name:  Chhatapur Election Year:  2005-Oct
AC No:  45 AC name:  Chhatapur Election Year:  2005-Feb
AC No:  46 AC name:  Narpatganj Election Year:  2010
AC No:  46 AC name:  Narpatganj Election Year:  2005-Oct
AC No:  46 AC name:  Narpatganj Election Year:  2005-Feb
AC No:  48 AC name:  Forbesganj Election Year:  2015
AC No:  48 AC name:  Forbesganj Election Year:  2005-Oct
AC No:  48 AC name:  Forbesganj Election Year:  2005-Feb
AC No:  49 AC name:  Araria Election Year:  2010
AC No:  49 AC name:  Araria Election Year:  2005-Oct
AC No:  49 AC name:  Araria Election Year:  2005-Feb
AC No:  50 AC name:  Jokihat Election Year:  2010
AC No:  50 AC name:  Jokihat Election Year:  2005-Oct
AC No:  50 AC name:  Jokihat Election Year:  2005-Feb
AC No:  51 AC name:  Sikti Election Year:  2010
AC No:  51 AC name:  Sikti Election Year:  2005-Oct
AC No:  51 AC name:  Sikti Election Year:  2005-Feb
AC No:  52 AC name:  Bahadurganj Election Year:  2010
AC No:  52 AC name:  Bahadurganj Election Year:  2015
AC No:  52 AC name:  Bahadurganj Election Year:  2005-Oct
AC No:  52 AC name:  Bahadurganj Election Year:  2005-Feb
AC No:  53 AC name:  Thakurganj Election Year:  2010
AC No:  53 AC name:  Thakurganj Election Year:  2005-Feb
AC No:  54 AC name:  Kishanganj Election Year:  2010
AC No:  54 AC name:  Kishanganj Election Year:  2005-Feb
AC No:  55 AC name:  Kochadhaman Election Year:  2010
AC No:  55 AC name:  Kochadhaman Election Year:  2015
AC No:  55 AC name:  Kochadhaman Election Year:  2005-Oct
AC No:  55 AC name:  Kochadhaman Election Year:  2005-Feb
AC No:  56 AC name:  Amour Election Year:  2010
AC No:  56 AC name:  Amour Election Year:  2005-Oct
AC No:  56 AC name:  Amour Election Year:  2005-Feb
AC No:  57 AC name:  Baisi Election Year:  2010
AC No:  57 AC name:  Baisi Election Year:  2015
AC No:  57 AC name:  Baisi Election Year:  2005-Oct
AC No:  57 AC name:  Baisi Election Year:  2005-Feb
AC No:  58 AC name:  Kasba Election Year:  2005-Oct
AC No:  58 AC name:  Kasba Election Year:  2005-Feb
AC No:  59 AC name:  Banmankhi Election Year:  2010
AC No:  59 AC name:  Banmankhi Election Year:  2015
AC No:  59 AC name:  Banmankhi Election Year:  2005-Feb
AC No:  60 AC name:  Rupauli Election Year:  2010
AC No:  60 AC name:  Rupauli Election Year:  2015
AC No:  61 AC name:  Dhamdaha Election Year:  2010
AC No:  61 AC name:  Dhamdaha Election Year:  2015
AC No:  61 AC name:  Dhamdaha Election Year:  2005-Oct
AC No:  61 AC name:  Dhamdaha Election Year:  2005-Feb
AC No:  62 AC name:  Purnia Election Year:  2010
AC No:  62 AC name:  Purnia Election Year:  2005-Oct
AC No:  63 AC name:  Katihar Election Year:  2010
AC No:  63 AC name:  Katihar Election Year:  2015
AC No:  63 AC name:  Katihar Election Year:  2005-Oct
AC No:  63 AC name:  Katihar Election Year:  2005-Feb
AC No:  64 AC name:  Kadwa Election Year:  2010
AC No:  64 AC name:  Kadwa Election Year:  2015
AC No:  64 AC name:  Kadwa Election Year:  2005-Oct
AC No:  64 AC name:  Kadwa Election Year:  2005-Feb
AC No:  65 AC name:  Balrampur Election Year:  2010
AC No:  65 AC name:  Balrampur Election Year:  2015
AC No:  65 AC name:  Balrampur Election Year:  2005-Oct
AC No:  65 AC name:  Balrampur Election Year:  2005-Feb
AC No:  66 AC name:  Pranpur Election Year:  2010
AC No:  66 AC name:  Pranpur Election Year:  2015
AC No:  66 AC name:  Pranpur Election Year:  2005-Oct
AC No:  66 AC name:  Pranpur Election Year:  2005-Feb
AC No:  67 AC name:  Manihari Election Year:  2010
AC No:  67 AC name:  Manihari Election Year:  2015
AC No:  67 AC name:  Manihari Election Year:  2005-Oct
AC No:  67 AC name:  Manihari Election Year:  2005-Feb
AC No:  68 AC name:  Barari Election Year:  2010
AC No:  68 AC name:  Barari Election Year:  2005-Oct
AC No:  68 AC name:  Barari Election Year:  2005-Feb
AC No:  69 AC name:  Korha Election Year:  2010
AC No:  69 AC name:  Korha Election Year:  2005-Feb
AC No:  70 AC name:  Alamnagar Election Year:  2010
AC No:  70 AC name:  Alamnagar Election Year:  2015
AC No:  70 AC name:  Alamnagar Election Year:  2005-Oct
AC No:  70 AC name:  Alamnagar Election Year:  2005-Feb
AC No:  71 AC name:  Bihariganj Election Year:  2010
AC No:  71 AC name:  Bihariganj Election Year:  2005-Oct
AC No:  71 AC name:  Bihariganj Election Year:  2005-Feb
AC No:  72 AC name:  Singheshwar Election Year:  2005-Oct
AC No:  72 AC name:  Singheshwar Election Year:  2005-Feb
AC No:  73 AC name:  Madhepura Election Year:  2005-Oct
AC No:  73 AC name:  Madhepura Election Year:  2005-Feb
AC No:  74 AC name:  Sonbarsa Election Year:  2010
AC No:  74 AC name:  Sonbarsa Election Year:  2005-Feb
AC No:  75 AC name:  Saharsa Election Year:  2010
AC No:  75 AC name:  Saharsa Election Year:  2005-Oct
AC No:  75 AC name:  Saharsa Election Year:  2005-Feb
AC No:  76 AC name:  Simri Bakhtiarpur Election Year:  2010
AC No:  76 AC name:  Simri Bakhtiarpur Election Year:  2015
AC No:  76 AC name:  Simri Bakhtiarpur Election Year:  2005-Oct
AC No:  76 AC name:  Simri Bakhtiarpur Election Year:  2005-Feb
AC No:  77 AC name:  Mahishi Election Year:  2010
AC No:  77 AC name:  Mahishi Election Year:  2015
AC No:  77 AC name:  Mahishi Election Year:  2005-Feb
AC No:  78 AC name:  Kusheshwar Asthan Election Year:  2010
AC No:  78 AC name:  Kusheshwar Asthan Election Year:  2005-Oct
AC No:  78 AC name:  Kusheshwar Asthan Election Year:  2005-Feb
AC No:  79 AC name:  Gora Bauram Election Year:  2010
AC No:  79 AC name:  Gora Bauram Election Year:  2015
AC No:  79 AC name:  Gora Bauram Election Year:  2005-Oct
AC No:  79 AC name:  Gora Bauram Election Year:  2005-Feb
AC No:  80 AC name:  Benipur Election Year:  2010
AC No:  80 AC name:  Benipur Election Year:  2005-Oct
AC No:  80 AC name:  Benipur Election Year:  2005-Feb
AC No:  81 AC name:  Alinagar Election Year:  2010
AC No:  81 AC name:  Alinagar Election Year:  2005-Oct
AC No:  81 AC name:  Alinagar Election Year:  2005-Feb
AC No:  82 AC name:  Darbhanga Rural Election Year:  2010
AC No:  82 AC name:  Darbhanga Rural Election Year:  2005-Feb
AC No:  83 AC name:  Darbhanga Election Year:  2005-Oct
AC No:  83 AC name:  Darbhanga Election Year:  2005-Feb
AC No:  84 AC name:  Hayaghat Election Year:  2010
AC No:  84 AC name:  Hayaghat Election Year:  2005-Oct
AC No:  84 AC name:  Hayaghat Election Year:  2005-Feb
AC No:  85 AC name:  Bahadurpur Election Year:  2010
AC No:  85 AC name:  Bahadurpur Election Year:  2005-Oct
AC No:  85 AC name:  Bahadurpur Election Year:  2005-Feb
AC No:  86 AC name:  Keoti Election Year:  2005-Oct
AC No:  86 AC name:  Keoti Election Year:  2005-Feb
AC No:  87 AC name:  Jale Election Year:  2010
AC No:  87 AC name:  Jale Election Year:  2005-Oct
AC No:  88 AC name:  Gaighat Election Year:  2010
AC No:  88 AC name:  Gaighat Election Year:  2015
AC No:  88 AC name:  Gaighat Election Year:  2005-Oct
AC No:  88 AC name:  Gaighat Election Year:  2005-Feb
AC No:  89 AC name:  Aurai Election Year:  2010
AC No:  89 AC name:  Aurai Election Year:  2005-Feb
AC No:  90 AC name:  Minapur Election Year:  2010
AC No:  90 AC name:  Minapur Election Year:  2005-Feb
AC No:  91 AC name:  Bochaha Election Year:  2005-Oct
AC No:  91 AC name:  Bochaha Election Year:  2005-Feb
AC No:  92 AC name:  Sakra Election Year:  2005-Oct
AC No:  92 AC name:  Sakra Election Year:  2005-Feb
AC No:  93 AC name:  Kurhani Election Year:  2010
AC No:  93 AC name:  Kurhani Election Year:  2005-Feb
AC No:  94 AC name:  Muzaffarpur Election Year:  2010
AC No:  94 AC name:  Muzaffarpur Election Year:  2005-Oct
AC No:  95 AC name:  Kanti Election Year:  2010
AC No:  95 AC name:  Kanti Election Year:  2015
AC No:  95 AC name:  Kanti Election Year:  2005-Oct
AC No:  95 AC name:  Kanti Election Year:  2005-Feb
AC No:  96 AC name:  Baruraj Election Year:  2010
AC No:  96 AC name:  Baruraj Election Year:  2005-Oct
AC No:  96 AC name:  Baruraj Election Year:  2005-Feb
AC No:  97 AC name:  Paroo Election Year:  2005-Oct
AC No:  97 AC name:  Paroo Election Year:  2005-Feb
AC No:  98 AC name:  Sahebganj Election Year:  2010
AC No:  98 AC name:  Sahebganj Election Year:  2015
AC No:  98 AC name:  Sahebganj Election Year:  2005-Oct
AC No:  99 AC name:  Baikunthpur Election Year:  2015
AC No:  99 AC name:  Baikunthpur Election Year:  2005-Oct
AC No:  100 AC name:  Barauli Election Year:  2005-Oct
AC No:  100 AC name:  Barauli Election Year:  2005-Feb
AC No:  101 AC name:  Gopalganj Election Year:  2005-Oct
AC No:  101 AC name:  Gopalganj Election Year:  2005-Feb
AC No:  102 AC name:  Kuchaikote Election Year:  2010
AC No:  102 AC name:  Kuchaikote Election Year:  2005-Oct
AC No:  102 AC name:  Kuchaikote Election Year:  2005-Feb
AC No:  103 AC name:  Bhorey Election Year:  2010
AC No:  103 AC name:  Bhorey Election Year:  2015
AC No:  103 AC name:  Bhorey Election Year:  2005-Feb
AC No:  104 AC name:  Hathua Election Year:  2010
AC No:  104 AC name:  Hathua Election Year:  2015
AC No:  104 AC name:  Hathua Election Year:  2005-Oct
AC No:  105 AC name:  Siwan Election Year:  2010
AC No:  105 AC name:  Siwan Election Year:  2015
AC No:  105 AC name:  Siwan Election Year:  2005-Oct
AC No:  105 AC name:  Siwan Election Year:  2005-Feb
AC No:  106 AC name:  Ziradei Election Year:  2010
AC No:  106 AC name:  Ziradei Election Year:  2015
AC No:  106 AC name:  Ziradei Election Year:  2005-Oct
AC No:  106 AC name:  Ziradei Election Year:  2005-Feb
AC No:  107 AC name:  Darauli Election Year:  2010
AC No:  107 AC name:  Darauli Election Year:  2015
AC No:  107 AC name:  Darauli Election Year:  2005-Oct
AC No:  107 AC name:  Darauli Election Year:  2005-Feb
AC No:  108 AC name:  Raghunathpur Election Year:  2010
AC No:  108 AC name:  Raghunathpur Election Year:  2015
AC No:  108 AC name:  Raghunathpur Election Year:  2005-Oct
AC No:  109 AC name:  Daraundha Election Year:  2010
AC No:  109 AC name:  Daraundha Election Year:  2005-Oct
AC No:  109 AC name:  Daraundha Election Year:  2005-Feb
AC No:  110 AC name:  Barharia Election Year:  2010
AC No:  110 AC name:  Barharia Election Year:  2005-Oct
AC No:  110 AC name:  Barharia Election Year:  2005-Feb
AC No:  111 AC name:  Goriyakothi Election Year:  2010
AC No:  111 AC name:  Goriyakothi Election Year:  2015
AC No:  111 AC name:  Goriyakothi Election Year:  2005-Feb
AC No:  112 AC name:  Maharajganj Election Year:  2010
AC No:  112 AC name:  Maharajganj Election Year:  2005-Feb
AC No:  113 AC name:  Ekma Election Year:  2010
AC No:  113 AC name:  Ekma Election Year:  2015
AC No:  113 AC name:  Ekma Election Year:  2005-Oct
AC No:  114 AC name:  Manjhi Election Year:  2010
AC No:  114 AC name:  Manjhi Election Year:  2015
AC No:  114 AC name:  Manjhi Election Year:  2005-Feb
AC No:  115 AC name:  Baniapur Election Year:  2010
AC No:  115 AC name:  Baniapur Election Year:  2005-Feb
AC No:  116 AC name:  Taraiya Election Year:  2010
AC No:  116 AC name:  Taraiya Election Year:  2005-Oct
AC No:  116 AC name:  Taraiya Election Year:  2005-Feb
AC No:  117 AC name:  Marhaura Election Year:  2010
AC No:  117 AC name:  Marhaura Election Year:  2005-Oct
AC No:  117 AC name:  Marhaura Election Year:  2005-Feb
AC No:  118 AC name:  Chapra Election Year:  2010
AC No:  118 AC name:  Chapra Election Year:  2015
AC No:  118 AC name:  Chapra Election Year:  2005-Oct
AC No:  118 AC name:  Chapra Election Year:  2005-Feb
AC No:  119 AC name:  Garkha Election Year:  2010
AC No:  119 AC name:  Garkha Election Year:  2005-Feb
AC No:  120 AC name:  Amnour Election Year:  2010
AC No:  120 AC name:  Amnour Election Year:  2015
AC No:  120 AC name:  Amnour Election Year:  2005-Oct
AC No:  120 AC name:  Amnour Election Year:  2005-Feb
AC No:  122 AC name:  Sonepur Election Year:  2005-Oct
AC No:  122 AC name:  Sonepur Election Year:  2005-Feb
AC No:  123 AC name:  Hajipur Election Year:  2010
AC No:  123 AC name:  Hajipur Election Year:  2005-Oct
AC No:  123 AC name:  Hajipur Election Year:  2005-Feb
AC No:  124 AC name:  Lalganj Election Year:  2010
AC No:  124 AC name:  Lalganj Election Year:  2015
AC No:  124 AC name:  Lalganj Election Year:  2005-Oct
AC No:  124 AC name:  Lalganj Election Year:  2005-Feb
AC No:  125 AC name:  Vaishali Election Year:  2005-Oct
AC No:  125 AC name:  Vaishali Election Year:  2005-Feb
AC No:  126 AC name:  Mahua Election Year:  2010
AC No:  127 AC name:  Raja Pakar Election Year:  2010
AC No:  127 AC name:  Raja Pakar Election Year:  2015
AC No:  127 AC name:  Raja Pakar Election Year:  2005-Oct
AC No:  127 AC name:  Raja Pakar Election Year:  2005-Feb
AC No:  128 AC name:  Raghopur Election Year:  2005-Oct
AC No:  128 AC name:  Raghopur Election Year:  2005-Feb
AC No:  129 AC name:  Manhar Election Year:  2010
AC No:  130 AC name:  Patepur Election Year:  2005-Oct
AC No:  130 AC name:  Patepur Election Year:  2005-Feb
AC No:  132 AC name:  Warisnagar Election Year:  2010
AC No:  132 AC name:  Warisnagar Election Year:  2005-Oct
AC No:  132 AC name:  Warisnagar Election Year:  2005-Feb
AC No:  134 AC name:  Ujiarpur Election Year:  2010
AC No:  134 AC name:  Ujiarpur Election Year:  2015
AC No:  134 AC name:  Ujiarpur Election Year:  2005-Oct
AC No:  134 AC name:  Ujiarpur Election Year:  2005-Feb
AC No:  135 AC name:  Morwa Election Year:  2010
AC No:  135 AC name:  Morwa Election Year:  2015
AC No:  135 AC name:  Morwa Election Year:  2005-Oct
AC No:  135 AC name:  Morwa Election Year:  2005-Feb
AC No:  136 AC name:  Sarairanjan Election Year:  2005-Oct
AC No:  136 AC name:  Sarairanjan Election Year:  2005-Feb
AC No:  137 AC name:  Mohiuddinnagar Election Year:  2015
AC No:  137 AC name:  Mohiuddinnagar Election Year:  2005-Oct
AC No:  137 AC name:  Mohiuddinnagar Election Year:  2005-Feb
AC No:  138 AC name:  Bibhutpur Election Year:  2010
AC No:  138 AC name:  Bibhutpur Election Year:  2015
AC No:  138 AC name:  Bibhutpur Election Year:  2005-Oct
AC No:  138 AC name:  Bibhutpur Election Year:  2005-Feb

    AC No        AC name Election Year
0       1  Valmiki Nagar          2010
1       1  Valmiki Nagar          2015
2       1  Valmiki Nagar      2005-Oct
3       1  Valmiki Nagar      2005-Feb
4       2       Ramnagar          2010
..    ...            ...           ...
636   243         Chakai          2010
637   243         Chakai          2015
638   243         Chakai      2005-Feb
639    42          Pipra      2005-Oct
640   131      Kalyanpur      2005-Oct

[641 rows x 3 columns]

In [ ]:
# 6th question Determine the stronghold party-seats. A stronghold seat is one that is won by the
# same party in all the elections.
ac_no_list = df['AC No'].unique()
election_year_list = df['Election Year'].unique()
output_6th_df = pd.DataFrame(columns=['AC No','AC name'])
for ac_no in ac_no_list:
  winning_party = []
  for election_year in election_year_list:
    if not df.loc[(df['AC No']==ac_no)&(df['Election Year']==election_year)]['Votes'].empty:
      idx = df.loc[(df['AC No']==ac_no)&(df['Election Year']==election_year)]['Votes'].idxmax()
      winning_party.append(df.loc[idx]['Party'])
  if len(winning_party) == 4:
    if winning_party[0] == winning_party[1] == winning_party[2] == winning_party[3]:
      # print(Stronghold party-seats)
      new_row = pd.DataFrame({'AC No':ac_no,'AC name':df.loc[df['AC No']==ac_no]['AC name'].unique()[0]},index=[0])
      output_6th_df = pd.concat([output_6th_df,new_row],ignore_index=True)
output_6th_df
        # idx = df.loc[(df['AC No']==ac_no)&(df['Party']==party)&(df['Election Year']==election_year)]['Votes'].idxmax()
        # winning_party.append(df.loc[idx]['Party'])
  # print(winning_party)

   AC No      AC name
0      7    Chanpatia
1      8      Bettiah
2     10       Raxaul
3     25      Parihar
4     41      Nirmali
5     72  Singheshwar
6    105        Siwan
7    112  Maharajganj
8    132   Warisnagar
9    149     Khagaria
10   153     Gopalpur
11   160     Dhuraiya
12   163       Belhar
13   176      Nalanda
14   202       Rajpur
15   215       Kurtha

In [19]:
from itertools import product

In [18]:
# 7th question: Determine close contest constituencies. Close contest seats are those in which
# the top 2 finishers had a difference of less than 10% votes. Find seats in which
# there was a close contest in all the elections. If there is no such seat, then relax
# the criteria to 15%.

ac_no_list = df['AC No'].unique()
election_year_list = df['Election Year'].unique()
output_7th_df = pd.DataFrame(columns=['AC No','AC name'])
for ac_no in ac_no_list:
  top_two_parties = []
  for election_year in election_year_list:
    top_two_parties_election_year = []
    if not df.loc[(df['AC No']==ac_no)&(df['Election Year']==election_year)]['Votes'].empty:
      idx1,idx2 = df.loc[(df['AC No']==ac_no)&(df['Election Year']==election_year)]['Votes'].nlargest(2).index
      votes_1 = False
      votes_2 = False
      if df.loc[idx1]['Votes %']:
        votes_1 = True
      if df.loc[idx2]['Votes %']:
        votes_2 = True
      if votes_1 == True and votes_2 == True and Decimal(df.loc[idx1]['Votes %'])-Decimal(df.loc[idx2]['Votes %']) < 10.00:
        top_two_parties_election_year.append((df.loc[idx1]['Party'], df.loc[idx2]['Party']))
        top_two_parties.append(top_two_parties_election_year)
  # list_c = [{1, 2}, {3}]
  # list_d = [{3}, {1, 2}]

  # # Convert to frozensets so they can be hashed/sorted for exact content comparison
  # def list_to_frozenset(lst):
  #     return sorted([frozenset(s) for s in lst])

  # print(list_to_frozenset(list_c) == list_to_frozenset(list_d))
  print(top_two_parties)
# all_pairs = [(a, b, a == b) for a, b in product(list_a, list_b)]
# print(all_pairs)
  # top_two_parties
  # break
  # if (Decimal(df.loc[idx1]['Votes %']-df.loc[idx2]['Votes %']) < 10.00:
  #       top_two_parties_election_year.append((df.loc[idx1]['Party'], df.loc[idx1]['Party']))
  #     # print(top_two_parties_election_year)
  #     top_two_parties.append(top_two_parties_election_year)
  # print(top_two_parties)
      # print(df.loc[idx2]['Votes %'])
      # top_two_parties.append(df.loc[idx]['Party'])

[[('Rashtriya Janata Dal', 'Samajwadi Party')], [('Rashtriya Janata Dal', 'Samajwadi Party')]]
[]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Lok Jan Shakti Party')]]
[[('Bharatiya Janta Party', 'Janata Dal (United)')], [('Bharatiya Janta Party', 'Nationalist Congress Party')]]
[[('Independent', 'Janata Dal (United)')], [('Indian National Congress', 'Samajwadi Party')], [('Samajwadi Party', 'Independent')]]
[[('Bharatiya Janta Party', 'Janata Dal (United)')], [('Janata Dal (United)', 'Bahujan Samaj Party')], [('Janata Dal (United)', 'Bahujan Samaj Party')]]
[[('Bharatiya Janta Party', 'Janata Dal (United)')]]
[[('Bharatiya Janta Party', 'Janata Dal (United)')], [('Bharatiya Janta Party', 'Independent')]]
[[('Independent', 'Janata Dal (United)')], [('Janata Dal (United)', 'Bharatiya Janta Party')], [('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Independent')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Communist Party Of India (MARXIST)')]]
[[('Janata Dal (United)', 'Lok Jan Shakti Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Lok Jan Shakti Party')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Janata Dal (United)', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Janata Dal (United)', 'Janata Dal (United)')], [('Bharatiya Janta Party', 'Independent')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Lok Jan Shakti Party', 'Janata Dal (United)')], [('Lok Jan Shakti Party', 'Janata Dal (United)')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Lok Jan Shakti Party')]]
[[('Independent', 'Janata Dal (United)')], [('Bahujan Samaj Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Bahujan Samaj Party')], [('Janata Dal (United)', 'Hindustani Awam Morcha (Secular)')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Indian National Congress')], [('Janata Dal (United)', 'Indian National Congress')]]
[[('Indian National Congress', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Bahujan Samaj Party')], [('Bahujan Samaj Party', 'Lok Jan Shakti Party')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Lok Jan Shakti Party')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Indian National Congress', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')]]
[[('Janata Dal (United)', 'Communist Party Of India')], [('Rashtriya Lok Samta Party', 'Indian National Congress')], [('Communist Party Of India (MARXIST-LENINIST) (LIBERATION)', 'Rashtriya Janata Dal')], [('Communist Party Of India (MARXIST-LENINIST) (LIBERATION)', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Janata Dal (United)', 'Indian National Congress')], [('Janata Dal (United)', 'Indian National Congress')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Janata Dal (United)', 'Indian National Congress')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Indian National Congress')], [('Independent', 'Janata Dal (United)')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Bharatiya Janta Party')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Janata Dal (United)', 'Bharatiya Janta Party')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Lok Jan Shakti Party')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Bharatiya Janta Party', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Janata Dal (United)')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Indian National Congress', 'Janata Dal (United)')], [('Indian National Congress', 'Bharatiya Janta Party')], [('Janata Dal (United)', 'Indian National Congress')], [('Janata Dal (United)', 'Indian National Congress')]]
[[('Lok Jan Shakti Party', 'Janata Dal (United)')], [('Janata Dal (United)', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Indian National Congress', 'Bharatiya Janta Party')], [('Indian National Congress', 'Bharatiya Janta Party')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Indian National Congress')], [('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Indian National Congress', 'Bharatiya Janta Party')], [('Indian National Congress', 'Bharatiya Janta Party')], [('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[]
[[('Bharatiya Janta Party', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Indian National Congress', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Independent', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')], [('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Nationalist Congress Party')], [('Bharatiya Janta Party', 'Nationalist Congress Party')], [('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Janata Dal (United)', 'Nationalist Congress Party')], [('Indian National Congress', 'Lok Jan Shakti Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Indian National Congress', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Bharatiya Janta Party', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Janata Dal (United)', 'Indian National Congress')], [('Indian National Congress', 'Independent')]]
[[('Independent', 'Indian National Congress')], [('Independent', 'Indian National Congress')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Communist Party Of India', 'Rashtriya Janata Dal')], [('Communist Party Of India', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Bharatiya Janta Party', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Independent')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Indian National Congress', 'Bharatiya Janta Party')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Samajwadi Party', 'Janata Dal (United)')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')], [('Independent', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Lok Jan Shakti Party')], [('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Bharatiya Janta Party', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Janata Dal (United)', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Janata Dal (United)')], [('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Lok Jan Shakti Party', 'Rashtriya Janata Dal')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Independent', 'Hindustani Awam Morcha (Secular)')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Bharatiya Janta Party', 'Janata Dal (United)')], [('Communist Party Of India (MARXIST)', 'Lok Jan Shakti Party')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Lok Jan Shakti Party')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')], [('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[[('Rashtriya Janata Dal', 'Lok Jan Shakti Party')]]
[]
[[('Bharatiya Janta Party', 'Janata Dal (United)')], [('Bharatiya Janta Party', 'Communist Party Of India')]]
[[('Bharatiya Janta Party', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')], [('Janata Dal (United)', 'Bharatiya Janta Party')], [('Communist Party Of India', 'Bharatiya Janta Party')], [('Communist Party Of India', 'Lok Jan Shakti Party')]]
[[('Bharatiya Janta Party', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')], [('Communist Party Of India (Marxist-Leninist) (Liberation)', 'Bharatiya Janta Party')], [('Indian National Congress', 'Communist Party Of India')], [('Independent', 'Communist Party Of India')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Bharatiya Janta Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Janata Dal (United)', 'Bahujan Samaj Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Bharatiya Janta Party')], [('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Indian National Congress', 'Lok Jan Shakti Party')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Bharatiya Janta Party', 'Indian National Congress')], [('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Indian National Congress')]]
[[('Bharatiya Janta Party', 'Janata Dal (United)')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[]
[[('Bharatiya Janta Party', 'Indian National Congress')]]
[[('Rashtriya Janata Dal', 'Lok Jan Shakti Party')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[]
[[('Janata Dal (United)', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Lok Jan Shakti Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Bharatiya Janta Party', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Indian National Congress')], [('Bharatiya Janta Party', 'Indian National Congress')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Samajwadi Party', 'Indian National Congress')], [('Indian National Congress', 'Samajwadi Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[]
[[('Independent', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Independent')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Samajwadi Party', 'Bharatiya Janta Party')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Bharatiya Janta Party', 'Samajwadi Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Lok Jan Shakti Party')], [('Bharatiya Janta Party', 'Nationalist Congress Party')], [('Nationalist Congress Party', 'Bharatiya Janta Party')]]
[[('Communist Party Of India', 'Independent')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Bharatiya Janta Party', 'Communist Party Of India')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Communist Party Of India (MARXIST-LENINIST) (LIBERATION)', 'Bharatiya Janta Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Indian National Congress', 'Janata Dal (United)')], [('Indian National Congress', 'Nationalist Congress Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Communist Party Of India')]]
[]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[]
[[('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Bharatiya Janta Party')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Indian National Congress', 'Janata Dal (United)')], [('Janata Dal (United)', 'Communist Party Of India')]]
[[('Bharatiya Janta Party', 'Indian National Congress')], [('Indian National Congress', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Lok Samta Party')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Lok Jan Shakti Party')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Janata Dal (United)')], [('Lok Jan Shakti Party', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Janata Dal (United)')], [('Rashtriya Janata Dal', 'Janata Dal (United)')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Rashtriya Janata Dal')], [('Janata Dal (United)', 'Lok Jan Shakti Party')], [('Janata Dal (United)', 'Independent')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Hindustani Awam Morcha (Secular)')], [('Janata Dal (United)', 'Lok Jan Shakti Party')], [('Lok Jan Shakti Party', 'Janata Dal (United)')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Lok Jan Shakti Party', 'Bharatiya Janta Party')]]
[[('Lok Jan Shakti Party', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Bharatiya Janta Party', 'Janata Dal (United)')]]
[[('Janata Dal (United)', 'Indian National Congress')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')]]
[[('Janata Dal (United)', 'Indian National Congress')], [('Janata Dal (United)', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Lok Jan Shakti Party')]]
[[('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Rashtriya Janata Dal', 'Bharatiya Janta Party')], [('Bharatiya Janta Party', 'Rashtriya Janata Dal')]]
[[('Janata Dal (United)', 'Bharatiya Janta Party')]]
[]

In [20]:
set1 = [1, 2]
set2 = ['A', 'B']
set3 = ['x', 'y']
set4 = [True, False]

# Nested loop in a single line
result = [(w, x, y, z) for w in set1 for x in set2 for y in set3 for z in set4]

In [21]:
result

[(1, 'A', 'x', True),
 (1, 'A', 'x', False),
 (1, 'A', 'y', True),
 (1, 'A', 'y', False),
 (1, 'B', 'x', True),
 (1, 'B', 'x', False),
 (1, 'B', 'y', True),
 (1, 'B', 'y', False),
 (2, 'A', 'x', True),
 (2, 'A', 'x', False),
 (2, 'A', 'y', True),
 (2, 'A', 'y', False),
 (2, 'B', 'x', True),
 (2, 'B', 'x', False),
 (2, 'B', 'y', True),
 (2, 'B', 'y', False)]

In [5]:
# 8th question
# Find the growing seats. For the top 8 parties at the state-level in the 2005-Feb
# Election, Determine the seats in which these parties have continuously increased
# their votes in the next 3 elections.
feb_2005_df = df.loc[df['Election Year']=='2005-Feb']
ac_no_list = df['AC No'].unique()
party_list = feb_2005_df.groupby(by=['Party'])['Votes'].sum().sort_values(ascending=False)[:9].index.tolist()
oct_2005_df = df.loc[df['Election Year']=='2005-Oct']
df_2010 = df.loc[df['Election Year']=='2010']
df_2015 = df.loc[df['Election Year']=='2015']
party_ac_no_dict = {}
for party in party_list:
  party_ac_no_dict[party] = []
for ac_no in ac_no_list:
  for party in party_list:
    feb_2005_value = df.loc[(df['AC No']==ac_no)&(df['Election Year']=='2005-Feb')&((df['Party']==party))]['Votes'].sum()
    oct_2005_value = df.loc[(df['AC No']==ac_no)&(df['Election Year']=='2005-Oct')&((df['Party']==party))]['Votes'].sum()
    value_2010 = df.loc[(df['AC No']==ac_no)&(df['Election Year']=='2010')&((df['Party']==party))]['Votes'].sum()
    value_2015 = df.loc[(df['AC No']==ac_no)&(df['Election Year']=='2015')&((df['Party']==party))]['Votes'].sum()
    if value_2015>value_2010>oct_2005_value>feb_2005_value:
      party_ac_no_dict[party].append(int(ac_no))
print(party_ac_no_dict)

{'Rashtriya Janata Dal': [13, 33, 38, 45, 75, 81, 82, 83, 90, 91, 92, 98, 115, 121, 128, 154, 172, 187, 203, 233, 241], 'Independent': [32, 33, 70, 76, 100, 105, 164, 178, 221, 238], 'Janata Dal (United)': [6, 9, 16, 18, 34, 39, 41, 43, 50, 61, 72, 102, 124, 149, 151, 157, 159, 160, 164, 166, 171, 174, 179, 193, 202, 209, 221, 226, 227, 231], 'Lok Jan Shakti Party': [74, 78, 84, 127, 141, 148], 'Bharatiya Janta Party': [7, 10, 11, 24, 28, 69, 75, 86, 94, 105, 106, 130, 143, 152, 156, 194, 195, 199, 206, 234, 235], 'Indian National Congress': [23, 62, 155, 183], 'Bahujan Samaj Party': [14, 18, 74, 160, 161, 188, 221, 224], 'Samajwadi Party': [16, 37, 209], 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)': []}

In [25]:
# Question 9: Find the declining seats. Repeat exercise g for the opposite growth.
ac_no_list = df['AC No'].unique()
election_year_list = df['Election Year'].unique()
output_7th_df = pd.DataFrame(columns=['AC No','AC name'])
for ac_no in ac_no_list:
  bottom_two_parties = []
  for election_year in election_year_list:
    bottom_two_parties_election_year = []
    if not df.loc[(df['AC No']==ac_no)&(df['Election Year']==election_year)]['Votes'].empty:
      idx1,idx2 = df.loc[(df['AC No']==ac_no)&(df['Election Year']==election_year)]['Votes'].nsmallest(2).index
      votes_1 = False
      votes_2 = False
      if df.loc[idx1]['Votes %']:
        votes_1 = True
      if df.loc[idx2]['Votes %']:
        votes_2 = True
      if votes_1 == True and votes_2 == True and Decimal(df.loc[idx1]['Votes %'])-Decimal(df.loc[idx2]['Votes %']) < 10.00:
        bottom_two_parties_election_year.append((df.loc[idx1]['Party'], df.loc[idx2]['Party']))
        bottom_two_parties.append(bottom_two_parties_election_year)
  print(bottom_two_parties)

[[('Independent', 'Independent')], [('Garib Janta Dal (Secular)', 'Communist Party Of India (Marxist-Leninist) (Liberation)')], [('Independent', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')], [('Communist Party Of India (MARXIST-LENINIST) (LIBERATION)', 'Independent')]]
[[('Akhil Bharatiya Ashok Sena', 'Independent')], [('Jan Adhikar Party (Loktantrik)', 'Independent')], [('Indian Justice Party', 'Samajwadi Party')], [('Independent', 'Shiv Sena')]]
[[('Rashtriya Krantikari Janata Party', 'Akhil Bharatiya Ashok Sena')], [('Bahujan Mukti Party', 'Janta Dal Rashtravadi')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Rashtra Sewa Dal', 'Independent')], [('Jharkhand Mukti Morcha', 'Samajwadi Party')], [('Independent', 'Independent')], [('Shiv Sena', 'Independent')]]
[[('Samajwadi Party', 'Rashtriya Krantikari Janata Party')], [('Sarvajan Kalyan Loktantrik Party', 'Shiv Sena')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Vanchitsamaj Insaaf Party', 'Janata Dal (Secular)')], [('Rashtriya Jankranti Party', 'Independent')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Indian Justice Party', 'Janvadi Party (Socialist)')], [('Gareeb Aadmi Party', 'Independent')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Jharkhand Mukti Morcha', 'Indian Justice Party')], [('National Janta Party (Indian)', 'Naya Daur Party')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Vanchitsamaj Insaaf Party', 'Nationalist Congress Party')], [('Rashtriya Samanta Dal', 'Independent')], [('Indian Justice Party', 'Samajwadi Party')], [('Independent', 'Independent')]]
[[('Samajwadi Party', 'Nationalist Congress Party')], [('Bhartiya Lokmat Rashtrwadi Party', 'Independent')], [('Independent', 'Samajwadi Party')], [('Independent', 'Samata Party')]]
[[('Independent', 'Independent')], [('Independent', 'Independent')], [('Independent', 'Independent')], [('Jharkhand Party', 'Samajwadi Party')]]
[[('Independent', 'Independent')], [('Independent', 'Gareeb Aadmi Party')], [('Independent', 'Samajwadi Party')], [('Independent', 'Independent')]]
[[('Independent', 'Jharkhand Mukti Morcha')], [('Sarvajan Kalyan Loktantrik Party', 'Jammu & Kashmir National Panthers Party')], [('Bahujan Samaj Party', 'Samajwadi Party')], [('Independent', 'Independent')]]
[[('Janata Dal (Secular)', 'Independent')], [('Jammu & Kashmir National Panthers Party', 'Aarakshan Virodhi Party')], [('Muslim League Kerala State Committee', 'Independent')], [('Independent', 'Independent')]]
[[('Independent', 'Independent')], [('Bahujan Samaj Party', 'Samajwadi Party')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Samajwadi Party', 'Independent')], [('Aap Aur Hum Party', 'Bahujan Mukti Party')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Rashtra Sewa Dal', 'Indian Justice Party')], [('Akhil Bharatiya Hind Kranti Party', 'Independent')], [('Independent', 'Samajwadi Party')], [('Independent', 'Independent')]]
[[('Independent', 'All India Forward Bloc')], [('Jharkhand Mukti Morcha', 'Samajwadi Party')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Janvadi Party (Socialist)', 'Smast Bhartiya Party')], [('Jan Adhikar Party (Loktantrik)', 'Sarvajan Kalyan Loktantrik Party')], [('Independent', 'Samajwadi Party')], [('Independent', 'Independent')]]
[[('Independent', 'Samajwadi Party')], [('Sarvajan Kalyan Loktantrik Party', 'Independent')], [('Bahujan Samaj Party', 'Rashtriya Janata Dal')], [('Shiv Sena', 'Independent')]]
[[('Nationalist Congress Party', 'Samajwadi Party')], [('Independent', 'Garib Janta Dal (Secular)')], [('Samajwadi Party', 'Independent')], [('Independent', 'Independent')]]
[[('Independent', 'Independent')], [('All India Forward Bloc', 'Independent')], [('Samajwadi Party', 'Lok Jan Shakti Party')], [('Akhil Bharatiya Ashok Sena', 'Independent')]]
[[('Smast Bhartiya Party', 'Revolutionary Socialist Party')], [('Bhartiya Jan Hitkari Party', 'Proutist Bloc India')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Samajwadi Party', 'Independent')], [('Jammu & Kashmir National Panthers Party', 'Rastriya Insaaf Party')], [('Akhil Bharat Hindu Mahasabha', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')], [('Independent', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')]]
[[('Samajwadi Party', 'Nationalist Congress Party')], [('Loktantrik Sarvjan Samaj Party', 'Socialist Party (India)')], [('Independent', 'Independent')], [('Samajwadi Party', 'Independent')]]
[[('Nationalist Congress Party', 'Independent')], [('Bahujan Samaj Party', 'Independent')], [('Samajwadi Party', 'Bharatiya Ekta Dal')], [('Samajwadi Party', 'Independent')]]
[[('Independent', 'Independent')], [('National Janta Party (Indian)', 'Samajwadi Party')], [('All India Forward Bloc', 'Independent')], [('Independent', 'Samajwadi Party')]]
[[('Samajwadi Party', 'Nationalist Congress Party')], [('Bahujan Mukti Party', 'Garib Janta Dal (Secular)')], [('Independent', 'Independent')], [('Bharat Mangalam Parishad', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')]]
[[('Bajjikanchal Vikas Party', 'Independent')], [('Independent', 'Bahujan Mukti Party')], [('Gondvana Gantantra Party', 'Samajwadi Party')], [('Independent', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')]]
[[('Nationalist Congress Party', 'Independent')], [('Akhil Bharat Hindu Mahasabha', 'Vanchitsamaj Insaaf Party')], [('Samajwadi Party', 'Bahujan Samaj Party')], [('Samajwadi Party', 'Independent')]]
[[('Independent', 'Janata Dal (Secular)')], [('Bhartiya Jagran Party', 'Aadarsh Mithila Party')], [('Gondvana Gantantra Party', 'Samajwadi Party')], [('Independent', 'Independent')]]
[[('Independent', 'Bahujan Ekta Party (R)')], [('Samajwadi Party', 'Garib Janta Dal (Secular)')], [('Samajwadi Party', 'Independent')], [('Independent', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')]]
[[('Independent', 'Independent')], [('All India Forward Bloc', 'Bhartiya Mitra Party')], [('Samajik Jantantrik Party', 'Independent')], [('Independent', 'Independent')]]
[[('Samajwadi Party', 'J & K National Panthers Party')], [('Hind Congress Party', 'Rashtriya Jankranti Party')], [('Rashtriya Lok Dal', 'Independent')], [('Independent', 'Independent')]]
[[('Bahujan Samaj Party', 'Krantikari Samyavadi Party')], [('Rashtriya Samanta Dal', 'Bahujan Samaj Party')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Nationalist Congress Party', 'Loktantrik Sarvjan Samaj Party')], [('Krantikari Samyavadi Party', 'Republican Party Of India (A)')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Samajwadi Party', 'Bahujan Ekta Party (R)')], [('Akhil Bhartiya Mithila Party', 'Samajwadi Janata Dal Democratic')], [('Samajwadi Party', 'Independent')], [('Independent', 'Independent')]]
[[('Samajwadi Party', 'Akhil Bharitya Mithila Party')], [('The National Road Map Party Of India', 'Samajwadi Janata Dal Democratic')], [('Rashtriya Lok Dal', 'Samata Party')], [('Independent', 'Independent')]]
[[('Independent', 'All India Forward Bloc')], [('Jammu & Kashmir National Panthers Party', 'Bhartiya Mitra Party')], [('Akhil Bharat Hindu Mahasabha', 'Independent')], [('Independent', 'Apna Dal')]]
[[('Independent', 'Independent')], [('Independent', 'Independent')], [('Samajwadi Party', 'Bahujan Samaj Party')], [('Independent', 'Apna Dal')]]
[[('J & K National Panthers Party', 'Independent')], [('Rashtriya Krantikari Samajwadi Party', 'Shiv Sena')], [('Gondvana Gantantra Party', 'Independent')], [('Independent', 'Independent')]]
[[('Rashtravadi Janata Party', 'Samajwadi Party')], [('Samajwadi Party', 'Lok Sewa Dal')], [('Bahujan Samaj Party', 'Independent')], [('Independent', 'Bahujan Samaj Party')]]
[[('J & K National Panthers Party', 'Independent')], [('The National Road Map Party Of India', 'Communist Party Of India (Marxist-Leninist) (Liberation)')], [('Independent', 'Independent')], [('Apna Dal', 'Independent')]]
[[('Independent', 'Independent')], [('Proutist Bloc India', 'Sarvajan Kalyan Loktantrik Party')], [('Independent', 'Samajwadi Party')], [('Independent', 'Rashtriya Lok Dal')]]
[[('Muslim League Kerala State Committee', 'Independent')], [('Rashtravadi Janata Party', 'Bahujan Mukti Party')], [('Bahujan Samaj Party', 'Lok Jan Shakti Party')], [('Independent', 'Independent')]]
[[('Rashtriya Jan-Jagram Morcha', 'Jharkhand Mukti Morcha')], [('Jharkhand Mukti Morcha', 'Loktantrik Janata Party (Secular)')], [('Bahujan Samaj Party', 'Jai Jawan Jai Kisan Mazdoor Congress')], [('Shiv Sena', 'Samajwadi Party')]]
[[('Jharkhand Mukti Morcha', 'Loktantrik Sarvjan Samaj Party')], [('Bharat Vikas Morcha', 'Communist Party Of India (Marxist-Leninist) (Liberation)')], [('Independent', 'Samata Party')], [('Krantikari Samyavadi Party', 'Independent')]]
[[('Independent', 'Nationalist Congress Party')], [('Socialist Janta Party', 'Independent')], [('Independent', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')], [('Independent', 'Independent')]]
[[('Independent', 'Independent')], [('Janta Dal Rashtravadi', 'Independent')], [('Bahujan Samaj Party', 'Lok Jan Shakti Party')], [('Krantikari Samyavadi Party', 'Samata Party')]]
[[('Samajwadi Party', 'Independent')], [('New All India Congress Party', 'Socialist Janta Party')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Independent', 'Independent')], [('Shiv Sena', 'Bahujan Nyay Dal')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Independent', 'Samajwadi Party')], [('Loktantrik Janata Party (Secular)', 'Communist Party Of India (Marxist-Leninist) (Liberation)')], [('Independent', 'Independent')], [('Independent', 'Samata Party')]]
[[('Samajwadi Party', 'Independent')], [('Indian Union Muslim League', 'Samajwadi Party')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Indian Justice Party', 'Independent')], [('Shiv Sena', 'Indian Union Muslim League')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Loktantrik Sarvjan Samaj Party', 'Bharatiya Jantantrik Janta Dal')], [('Garib Janta Dal (Secular)', 'Bharat Nirman Party')], [('Independent', 'Apna Dal')], [('Independent', 'Independent')]]
[[('Nationalist Congress Party', 'Independent')], [('All India Forward Bloc', 'Garib Janta Dal (Secular)')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Loktantrik Sarvjan Samaj Party', 'Socialist Janta Party')], [('Lok Dal', 'Indian Union Muslim League')], [('Independent', 'Samajwadi Party')], [('Independent', 'Rashtriya Lok Dal')]]
[[('Bharatiya Jantantrik Janta Dal', 'Bahujan Samaj Party')], [('Bahujan Mukti Party', 'Bhartiya Jantantrik Janata Dal')], [('Independent', 'Independent')], [('Lok Sewa Dal', 'Independent')]]
[[('Samajwadi Party', 'Lokpriya Samaj Party')], [('Aap Aur Hum Party', 'Independent')], [('Independent', 'Independent')], [('Samajwadi Party', 'Independent')]]
[[('Samajwadi Party', 'All India Forward Bloc')], [('Lok Dal', 'Independent')], [('Samajwadi Party', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')], [('Shiv Sena', 'Independent')]]
[[('All India Forward Bloc', 'Bharatiya Jantantrik Janta Dal')], [('All India Forward Bloc (Subhasist)', 'Independent')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Bahujan Shakty', 'Akhil Bharatiya Jan Sangh')], [('Rashtra Sewa Dal', 'Aap Aur Hum Party')], [('Independent', 'Bahujan Samaj Party')], [('Independent', 'Independent')]]
[[('Independent', 'Independent')], [('Jharkhand Mukti Morcha', 'Bahujan Mukti Party')], [('Samajwadi Party', 'Bahujan Samaj Party')], [('Independent', 'Independent')]]
[[('Independent', 'Bahujan Samaj Party')], [('Bahujan Mukti Party', 'Vanchitsamaj Insaaf Party')], [('Independent', 'Akhil Jan Vikas Dal')], [('Independent', 'Krantikari Samyavadi Party')]]
[[('Bharatiya Momin Front', 'Independent')], [('Bahujan Kranti Party (Marxwad-Ambedkarwad)', 'Bharat Nirman Party')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Indian Justice Party', 'Independent')], [('Bahujan Mukti Party', 'Independent')], [('Independent', 'Samata Party')], [('Independent', 'Independent')]]
[[('Janata Dal (Secular)', 'Bahujan Samaj Party')], [('Indian Union Muslim League', 'Bahujan Mukti Party')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Independent', 'Independent')], [('Ittehad-E-Millait Council', 'Janta Dal Rashtravadi')], [('Independent', 'Samajwadi Party')], [('Independent', 'Samajwadi Party')]]
[[('Independent', 'Bahujan Samaj Party')], [('Bahujan Mukti Party', 'Janta Dal Rashtravadi')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Independent', 'Independent')], [('Independent', 'Independent')], [('Samata Party', 'Independent')], [('Independent', 'Independent')]]
[[('Jawan Kisan Morcha', 'Bahujan Samaj Party')], [('Garib Janta Dal (Secular)', 'The National Road Map Party Of India')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Rashtra Sewa Dal', 'Bahujan Samaj Party')], [('The National Road Map Party Of India', 'Maanavvaadi Janta Party')], [('Rashtriya Lok Dal', 'Communist Party Of India')], [('Independent', 'Independent')]]
[[('Independent', 'Janata Dal (Secular)')], [('Bahujan Samaj Party', 'Bahujan Mukti Party')], [('Bahujan Samaj Party', 'Rashtriya Lok Dal')], [('Bahujan Samaj Party', 'Independent')]]
[[('Janata Dal (Secular)', 'Independent')], [('National Janta Party (Indian)', 'Bahujan Mukti Party')], [('Samajwadi Party', 'Independent')], [('Independent', 'Bahujan Samaj Party')]]
[[('Independent', 'Independent')], [('Rashtravadi Janata Party', 'Communist Party Of India (Marxist-Leninist) (Liberation)')], [('Independent', 'Bahujan Samaj Party')], [('Bahujan Samaj Party', 'Indian Justice Party')]]
[[('Indian Justice Party', 'Independent')], [('National Janta Party (Indian)', 'Independent')], [('Indian Justice Party', 'Samajwadi Party')], [('Independent', 'Independent')]]
[[('Indian Justice Party', 'Samajwadi Party')], [('Bharat Nirman Party', 'Sarvajan Kalyan Loktantrik Party')], [('Samajwadi Party', 'Independent')], [('Samajwadi Party', 'Independent')]]
[[('Janata Dal (Secular)', 'Rashtra Sewa Dal')], [('Independent', 'Independent')], [('Bahujan Samaj Party', 'Samajwadi Party')], [('Independent', 'Bahujan Samaj Party')]]
[[('Samajwadi Party', 'Independent')], [('National Janta Party (Indian)', 'Sarvajan Kalyan Loktantrik Party')], [('Communist Party Of India (MARXIST-LENINIST) (LIBERATION)', 'Samajwadi Party')], [('Communist Party Of India (MARXIST-LENINIST) (LIBERATION)', 'Independent')]]
[[('Indian Justice Party', 'Samajwadi Party')], [('Sarvajan Kalyan Loktantrik Party', 'Independent')], [('Rashtriya Lok Dal', 'Independent')], [('Independent', 'Independent')]]
[[('Independent', 'Janata Dal (Secular)')], [('Bhartiya Janhit Dal', 'Shiv Sena')], [('Bahujan Samaj Party', 'Independent')], [('Independent', 'Bahujan Samaj Party')]]
[[('Independent', 'Bahujan Samaj Party')], [('Lok Awaz Dal', 'Bhartiya Janhit Dal')], [('Janata Dal (Secular)', 'Independent')], [('Independent', 'Krantikari Samyavadi Party')]]
[[('Samajwadi Party', 'Independent')], [('National Janta Party (Indian)', 'Independent')], [('Independent', 'Independent')], [('Independent', 'Independent')]]
[[('Samajwadi Party', 'Independent')], [('Hind Congress Party', 'National Janta Party (Indian)')], [('Bahujan Samaj Party', 'Rashtravadi Janata Party')], [('Rashtravadi Janata Party', 'Bahujan Samaj Party')]]
[[('Muslim League Kerala State Committee', 'Independent')], [('Samajwadi Party', 'Sarvajan Kalyan Loktantrik Party')], [('Bahujan Samaj Party', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')], [('Independent', 'Bahujan Samaj Party')]]
[[('Independent', 'Nationalist Congress Party')], [('National Janta Party (Indian)', 'Samras Samaj Party')], [('Bahujan Samaj Party', 'Independent')], [('Samajwadi Party', 'Independent')]]
[[('Samajwadi Party', 'Indian National Green Party')], [('Bahujan Mukti Party', 'Bhartiya Janhit Dal')], [('Independent', 'Bahujan Samaj Party')], [('Independent', 'Apna Dal')]]
[[('Loktantrik Sarvjan Samaj Party', 'Janvadi Party (Socialist)')], [('Bharatiya Yuva Party (Democratic)', 'All India Forward Bloc')], [('Rashtriya Lok Dal', 'Samata Party')], [('Apna Dal', 'Independent')]]
[[('Samajwadi Party', 'Rashtriya Pragati Party')], [('National Lokmat Party', 'Akhil Bharatiya Hind Kranti Party')], [('Independent', 'Rashtriya Lok Dal')], [('Marxist Communist Party Of India (S.S.SRIVASTAVA)', 'Samajwadi Party')]]
[[('Bahujan Samaj Party', 'Bharatiya Jan Kranti Dal (Democratic)')], [('Republican Party Of India (A)', 'Akhil Bharat Hindu Mahasabha')], [('Independent', 'Independent')], [('Samajwadi Party', 'Rashtriya Lok Dal')]]
[[('Bahujan Samaj Party', 'Samajwadi Party')], [('Garib Janta Dal (Secular)', 'Bharat Nirman Party')], [('Bahujan Samaj Party', 'Rashtriya Lok Dal')], [('Independent', 'Krantikari Samyavadi Party')]]
[[('Rashtriya Pragati Party', 'Samajwadi Janata Party (RASHTRIYA)')], [('Garib Janta Dal (Secular)', 'Independent')], [('Bahujan Samaj Party', 'Jai Prakash Janata Dal')], [('Samajwadi Party', 'Lok Jan Shakti Party')]]
[[('Independent', 'Rashtra Sewa Dal')], [('Bharti Samudaya Party', 'Aap Aur Hum Party')], [('Samajwadi Party', 'Independent')], [('Independent', 'Bahujan Samaj Party')]]
[[('Independent', 'Independent')], [('Rashtravadi Janata Party', 'Bajjikanchal Vikas Party')], [('Samajwadi Party', 'Independent')], [('Rashtriya Lok Dal', 'Independent')]]
[[('Loktantrik Sarvjan Samaj Party', 'Nationalist Congress Party')], [('Janta Dal Rashtravadi', 'Rashtriya Mahan Gantantra Party')], [('Communist Party Of India (MARXIST-LENINIST) (LIBERATION)', 'Shiv Sena')], [('Samajwadi Party', 'Independent')]]
[[('Loktantrik Sarvjan Samaj Party', 'Independent')], [('Independent', 'Samajwadi Party')], [('Bahujan Samaj Party', 'Jai Jawan Jai Kisan Mazdoor Congress')], [('Bahujan Samaj Party', 'Independent')]]
[[('Independent', 'Independent')], [('Bhartiya Janhit Dal', 'Sarvajan Kalyan Loktantrik Party')], [('Bahujan Samaj Party', 'Independent')], [('Independent', 'Samajwadi Party')]]
[[('Loktantrik Samata Dal', 'Samajwadi Party')], [('Rajnaitik Vikalp Party', 'Garib Janta Dal (Secular)')], [('Bahujan Samaj Party', 'Independent')], [('Independent', 'Communist Party Of India (MARXIST-LENINIST) (LIBERATION)')]]
[[('Rashtriya Jan-Jagram Morcha', 'Samajwadi Party')], [('Janta Dal Rashtravadi', 'Bharatiya Bahujan Congress')], [('Bahujan Samaj Party', 'Independent')], [('Independent', 'Independent')]]
[[('Samajwadi Party', 'Indian Justice Party')], [('Socialist Party (India)', 'Samajwadi Party')], [('Bahujan Samaj Party', 'Independent')], [('Apna Dal', 'Bahujan Samaj Party')]]
[[('Samajwadi Party', 'Indian Justice Party')], [('Samajwadi Party', 'Bahujan Kranti Party (Marxwad-Ambedkarwad)')], [('Independent', 'Bahujan Samaj Party')], [('Nationalist Congress Party', 'Indian National Congress')]]
[[('Independent', 'Nationalist Congress Party')], [('Bahujan Samaj Party', 'Independent')], [('Independent', 'Independent')], [('Independent', 'Samajwadi Janata Party (RASHTRIYA)')]]
[[('Samajwadi Party', 'Indian Justice Party')], [('Bharatiya Ekta Dal', 'Bhartiya Janhit Dal')], [('Samajwadi Party', 'Bahujan Samaj Party')], [('Samajwadi Party', 'Bahujan Samaj Party')]]
[[('Independent', 'Independent')], [('Independent', 'Loktantrik Janata Party (Secular)')], [('Independent', 'Bahujan Samaj Party')], [('Independent', 'Bahujan Samaj Party')]]
[[('Loktantrik Sarvjan Samaj Party', 'Independent')], [('Swatantra Samaj Party', 'Rashtriya Samanta Dal')], [('Bahujan Samaj Party', 'Independent')], [('Independent', 'Independent')]]

In [11]:
# Question 10: Determine the state-winner-match constituencies. Find the seats which have
# always elected the party that has gone on to win the state election (most votes
# secured at state). So if the RJD won at the state level in 2010, then seats which
# voted an RJD candidate as winner are considered in this category. This criteria
# for a seat has to be matched for each election.
feb_2005_df = df.loc[df['Election Year']=='2005-Feb']
print("Feb 2005 elections winner: ",feb_2005_df.groupby(by=['Party'])['Votes'].sum().idxmax()," votes: ", feb_2005_df.groupby(by=['Party'])['Votes'].sum().max())
oct_2005_df = df.loc[df['Election Year']=='2005-Oct']
print("Oct 2005 elections winner: ",oct_2005_df.groupby(by=['Party'])['Votes'].sum().idxmax()," votes: ", oct_2005_df.groupby(by=['Party'])['Votes'].sum().max())
df_2010 = df.loc[df['Election Year']=='2010']
print("2010 elections winner: ",df_2010.groupby(by=['Party'])['Votes'].sum().idxmax()," votes: ", df_2010.groupby(by=['Party'])['Votes'].sum().max())
# print(df_2010.groupby(by=['Party'])['Votes'].sum())
df_2015 = df.loc[df['Election Year']=='2015']
print("2015 elections winner: ",df_2015.groupby(by=['Party'])['Votes'].sum().idxmax()," votes: ", df_2015.groupby(by=['Party'])['Votes'].sum().max())

# Feb 2005 elections winner:  Rashtriya Janata Dal  votes:  6140223
# Oct 2005 elections winner:  Rashtriya Janata Dal  votes:  5525081
# 2010 elections winner:  Janata Dal (United)  votes:  6561906
# 2015 elections winner:  Bharatiya Janta Party  votes:  9308015
ac_no_list = df['AC No'].unique()
state_winner_match = {}
state_winner_match['Rashtriya Janata Dal-Feb 2005']=[]
state_winner_match['Rashtriya Janata Dal-Oct 2005']=[]
state_winner_match['Janata Dal (United)-2010']=[]
state_winner_match['Bharatiya Janta Party-2015']=[]
for ac_no in ac_no_list:
  if not df.loc[(df['Election Year']=='2005-Feb')&(df['AC No']==ac_no)]['Votes'].empty:
    idx = df.loc[(df['Election Year']=='2005-Feb')&(df['AC No']==ac_no)]['Votes'].idxmax()
    winner_row = df.loc[idx]
    if winner_row['Party']=='Rashtriya Janata Dal':
      state_winner_match['Rashtriya Janata Dal-Feb 2005'].append(int(winner_row['AC No']))
  if not df.loc[(df['Election Year']=='2005-Oct')&(df['AC No']==ac_no)]['Votes'].empty:
    idx = df.loc[(df['Election Year']=='2005-Oct')&(df['AC No']==ac_no)]['Votes'].idxmax()
    winner_row = df.loc[idx]
    if winner_row['Party']=='Rashtriya Janata Dal':
      state_winner_match['Rashtriya Janata Dal-Oct 2005'].append(int(winner_row['AC No']))
  if not df.loc[(df['Election Year']=='2010')&(df['AC No']==ac_no)]['Votes'].empty:
    idx = df.loc[(df['Election Year']=='2010')&(df['AC No']==ac_no)]['Votes'].idxmax()
    winner_row = df.loc[idx]
    if winner_row['Party']=='Janata Dal (United)':
      state_winner_match['Janata Dal (United)-2010'].append(int(winner_row['AC No']))
  if not df.loc[(df['Election Year']=='2015')&(df['AC No']==ac_no)]['Votes'].empty:
    idx = df.loc[(df['Election Year']=='2015')&(df['AC No']==ac_no)]['Votes'].idxmax()
    winner_row = df.loc[idx]
    if winner_row['Party']=='Bharatiya Janta Party':
      state_winner_match['Bharatiya Janta Party-2015'].append(int(winner_row['AC No']))
print(state_winner_match)

Feb 2005 elections winner:  Rashtriya Janata Dal  votes:  6140223
Oct 2005 elections winner:  Rashtriya Janata Dal  votes:  5525081
2010 elections winner:  Janata Dal (United)  votes:  6561906
2015 elections winner:  Bharatiya Janta Party  votes:  9308015
{'Rashtriya Janata Dal-Feb 2005': [1, 11, 15, 16, 22, 26, 27, 29, 32, 43, 44, 46, 50, 53, 55, 60, 61, 63, 64, 66, 70, 71, 77, 79, 82, 85, 86, 87, 88, 91, 92, 93, 96, 100, 102, 103, 114, 115, 128, 135, 137, 142, 145, 147, 151, 152, 154, 156, 157, 161, 162, 169, 170, 185, 192, 193, 199, 200, 208, 210, 211, 212, 213, 217, 218, 221, 222, 227, 229, 234, 235, 236, 237, 238, 240], 'Rashtriya Janata Dal-Oct 2005': [1, 15, 18, 22, 26, 27, 28, 38, 44, 46, 49, 50, 60, 61, 65, 66, 70, 71, 83, 84, 85, 87, 88, 91, 92, 96, 97, 98, 100, 102, 124, 125, 135, 145, 147, 152, 154, 158, 161, 172, 192, 193, 196, 200, 210, 213, 221, 222, 226, 227, 229, 234, 237, 238], 'Janata Dal (United)-2010': [1, 4, 6, 12, 14, 16, 17, 18, 22, 26, 27, 29, 30, 31, 38, 39, 40, 41, 43, 44, 45, 50, 60, 61, 67, 70, 71, 72, 74, 76, 79, 85, 90, 91, 92, 93, 95, 98, 99, 102, 104, 109, 110, 112, 113, 114, 120, 121, 124, 125, 126, 127, 128, 132, 135, 136, 138, 140, 141, 144, 145, 148, 149, 150, 153, 157, 158, 159, 160, 163, 164, 165, 166, 169, 170, 171, 172, 174, 175, 176, 177, 178, 179, 181, 188, 189, 196, 201, 202, 204, 207, 209, 210, 213, 215, 216, 217, 218, 219, 221, 222, 224, 226, 227, 228, 231, 233, 237, 238, 239, 240, 241, 242], 'Bharatiya Janta Party-2015': [2, 4, 5, 6, 7, 8, 10, 11, 18, 19, 20, 25, 37, 45, 48, 51, 59, 62, 63, 66, 71, 83, 87, 93, 94, 96, 97, 99, 101, 105, 118, 120, 123, 161, 168, 179, 180, 181, 182, 183, 184, 186, 203, 204, 206, 219, 225, 230, 236, 239, 242]}